### ISSUE TITLE
Add bookmarks feature

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#1002]
It would be nice to be able to bookmark specific nodes in the treeview that the user uses a lot.

This would help so much when you are continously going back and forth between different places in the tree view, for example, my usual workflow is looking for files on global content, modifying my Tiled screen, playing the level and going back to my "DebugVariables" class which holds options to debug the scenes I create. If I had "DebugVariables" bookmarked I could switch to it instantly and change the options without having to mess with the tree view. The same way, I could bookmark my "Screens" global content folder and access it super fast.

**Proposed UI**

A right-click option "Add bookmark" for tree nodes.

![imaxe](https://user-images.githubusercontent.com/24922404/226888232-19a14323-c1e2-4e2a-8fba-d2973b45fb5f.png)

A button in Glue's toolbar is created. When you click it it will take you to the specific tree node it references. Its right-click menu would let you remove the bookmark.

![imaxe](https://user-images.githubusercontent.com/24922404/226890059-3f608678-d204-40b5-86a2-8b9a05141ad1.png)

**Comment by vchelaru** [comment]
I like this feature a lot, but I have a concern about the layout. If the button displays the text (such as "DebugVariables-Variables"), that will take up a lot of space. After a few bookmarks, you'd fill up the entire width of Glue. Then what, do we stack the buttons? Do we have a scroll bar?

The other concern is that the buttons would be text, and once you have a few of them up there, that's a lot of reading. It might be easier at-a-glance if we used icons similar to the toolbar.

Finally, we already have a toolbar for live edit where you can add objects with previews. It acts as a form of bookmark bar, but for creating objects in realtime. Maybe the two should be merged? Otherwise, users may have 2 toolbars which both contain objects, but which aren't necessarily useful.

However, now that I type it out, I realize that the toolbar for adding new instances is only for entities. You may want to bookmark any tree node.

What if there's a bookmarks treenode at the top of the tree view which defaults to expanded, and you could drag+drop bookmarks there. 

Here's what it might look like:

![image](https://user-images.githubusercontent.com/729631/227718900-574ef981-a53c-4152-9a7d-0a441542034b.png)

**Comment by mfigueirido** [comment]
My mock was just a rough approximation to get the idea :) and I think all you say makes a lot of sense.

To fix most of your concerns regarding having it at the app toolbar area you could have a single "bookmarks" button which shows a drop down listing all bookmarks. Your option is cool, I like it, but that requires to scroll up the tree view to access the bookmarks. Splitting into two different trees would fix that.

About the live edit toolbar... I can't say anything because I've never used it but yeah, I would like to bookmark any kind of node... that's the main objective I think.

**Comment by vchelaru** [comment]
Done 

03052258ccd75f98317b394c6ad7e493d975bd97

**Comment by mfigueirido** [comment]
There's a minor issue that remains, these are the steps:

1. Click on a bookmark. The referenced node will select in the lower tree view.
2. Click "Collapse all". All nodes collapse.
3. Click the last bookmark you already clicked on step 1 and see that the tree view doesn't expand because the selected node didn't change. I think it should always expand regardless of this.

**Comment by mfigueirido** [comment]
Another small request. Preserving splitter's bookmarks/tree view height ratio between sessions.
