### ISSUE TITLE
Glue should warn about instances that are their container?

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#1052]
I had a problem where an animated engine sprite was positioned unexpectedly. It took me a long time of inspecting generated code and trying to figure out why Glue behaved strangely with this one specific Sprite. It turns out that long ago I set the `SpriteInstance`'s `IsContainer` property to `true` for performance. This took a surprising amount of time to figure out and there is an opportunity to make this more clear in the Editor's UI and behavior.

It's worth noting that this was causing strange behavior in Glue edit mode. First, I was allowed to set the Relative properties, which has confusing consequences. Second, the Sprite had no bounding box when selected. It makes sense in retrospect but it was confusing at the time.

Some potential fixes:

1. Colorize instances that are the container or show a special icon
2. Warn or disallow setting Relative properties on instances that are their container
3. Show a bounding box on instances that are their container but maybe colorize it red or some other warning color

**Comment by vchelaru** [comment]
New icon:

![image](https://user-images.githubusercontent.com/729631/236571539-88901f0b-57c6-4381-96ba-3489cefc219d.png)

**Comment by vchelaru** [comment]
New text in variables:

![image](https://user-images.githubusercontent.com/729631/236624910-1aa7ad03-0d4b-44f2-a386-01ec0db9c5fb.png)

**Comment by vchelaru** [comment]
Edit mode issues are probably something I need to come back to later since that's more complicated (there's lots of other considerations). In the meantime, I believe that these two changes would make the problem a little easier to figure out in the future. Please re-open with comments if you disagree and would like more attention given to edit mode.

b9fff6c250238dfb59fb790094bbb05d58cb003b
