### ISSUE TITLE
Allow Glue content to be marked as "include in project = false"

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#1072]
I'm going to pack all my content into atlases with the help of a new plugin. I want this content I'll use to generate the atlasses to be part of Glue because that way I can reference it, track file system changes or simply browse the files, but I don't want them to be part of the project.

Adding a new property to turn off the Visual Studio project reference, which could be set in wildcards, would be really helpful.

**Comment by mfigueirido** [comment]
Update: Also, I would like to know if there's a way to make my Global Content files not generate any content properties at all. I want the files to be browsable but I'm not interested in the properties because I'm using naming conventions and I'd prefer not having to care about naming clashes.

**Comment by mfigueirido** [comment]
Oh, I just remembered the "IncludeDirectoryRelativeToContainer": true workaround which solves my second problem. You can ignore that one!

**Comment by vchelaru** [comment]
Update 1- This is being worked on, and files can now be excluded through a new "Settings" UI. This will eventually replace the old Properties tab. It was needed due to some details of how Property Grids work in Windows Forms.

By changing the value, a plugin catches that the excluded properties value has changed and updates the project membership appropriately. However, the plugin currently doesn't react to a changed file (a .gluj or entity/screen), it doesn't handle wildcards, and it doesn't handle adding/removing files on project reload. Therefore, the same logic needs to be applied in all of those scenarios for wildcards to work properly.

**Comment by vchelaru** [comment]
Fixed d61547162e8652b304840baf16f3aa5d5c81df21
