### ISSUE TITLE
Gum should handle inconsistent nesting gracefully?

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#1076]
This is a pretty obscure issue and may not be worth fixing at all. Here's the steps:

1. I have a ListBox that has author-time added components
2. Two of the components are old components where I had manually-specified parent container using dot syntax (predating the `DefaultChildrenContainer` functionality
3. I added a _new_ component to the ListBox
4. In the treeview, all three components (two old, one new) appears to be "inside" the ListBox instance
5. Items could not be sorted or rearranged
6. Upon inspection I realized that the new component parent was simply "ListBox" because I had not set a default child container yet. The older components parent was the `InnerPanelInstance`
7. So the items visually appeared to be at the same level and to have the same parent but actually one component was a child of the ListBox and the others were children of the ListBox InnerPanelInstance

I don't have opinions on a fix or even if we should fix it. This problem will naturally go away as we work the kinks out of the new child container feature.

**Comment by vchelaru** [comment]
Flagging this as **wontfix** for a number of reasons:

1. As the original bug states, this occurred due to a project being in a "transition period" between the old parenting system and the new parenting system. As the new system becomes more standardized, this will be less and less likely.
2. This behavior is potentially beneficial. In most cases children of an object should all be attached to the same parent, but not always. There may be times when an instance may be decorated with additional elements, such as an icon being added to a title bar, or a label being added to a footer. These one-offs may be desirable in the future, especially given...
3. The possibility for referencing components from external Gum projects. In this situation, a Gum component may not be editable if it comes from a shared project. Allowing mixed parents makes these imported elements even more flexible.
