### ISSUE TITLE
Forms TextBox options to ignore certain types of characters

### ISSUE THREAD

**Issue by Leheetu** [vchelaru/FlatRedBall#1090]
Option to make TextBox ignore certain characters from being typed
-Could be limited to allowing numbers only, for example
-Option to ignore all special characters?
-Maybe ability to blacklist/whitelist specified characters

**Comment by vchelaru** [comment]
The WPF solution is to have a "preview" event on the TextBox which allows the handling of events before the text box has a chance to process each character.

This is a proven pattern, so it might be worth incorporating. 

Example here:
https://stackoverflow.com/questions/1268552/how-do-i-get-a-textbox-to-only-accept-numeric-input-in-wpf

Questions for Vic to answer:
* Is the Preview pattern something we want throughout Forms, and this introduces it?
* Do we want to have the same EventArgs derived types ? 
* How does this play with IInputReceiver? If the code for adding letters to the text box goes through IInputReciever rather than TextBox, then the Preview function is needed on IInputReciever...unless it can pass to the TextBox which itself raises the Preview method. This might actually be desirable so we don't add new properties to IInputReciver, and TextBox needs to raise its own events anyway.

**Comment by vchelaru** [comment]
Fixed 501563b160c1048ca4031e0c3c56d4c366c9b9d1
