### ISSUE TITLE
Gum should offer "auto elipses" as an option on text

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#1102]
It's not easy to build a system for Gum that truncates text and adds elipses. It would be nice if Gum had options to automatically truncate text to fit with elipses. If this were built, Gum would have three options for text overflow:

- Wrap
- Clip
- Elipses

**Comment by vchelaru** [comment]
The feature cannot be implemented with the three options listed above, because it is possible to have a combination of wrap and ellipsis. For example, you may want a description to have 5 lines of text, and then after the 5th line to have ellipsis. 

To support the desired cases, the following are probably needed:

1. MaxNumberOfLines variable. If null (default), then text can have any number of lines. If set, then text will truncate after the fixed number of lines.
2. TruncationStyle - Choose between Truncate End (default) and Ellipsis.  This will be an enum value rather than bool because future versions may include other options such as Scale Down, Truncate Start, etc...
3. Vertical Size Line Behavior - Spill Over and Set Max Lines. If Set Max Lines, then the MaximumNumberOfLines will be internally set based on the height of the container

**Comment by vchelaru** [comment]
3ade148a4423f73df353ed764f4d7cae6394ce1a
