### ISSUE TITLE
Gum/Runtime should support Responsive-Design-Like concepts

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#1103]
## Problem Statement

In many games, eg Masteroid, you may have complex layouts that need to look great on a variety of resolutions and display densities from mobile/handheld, to sub 1080p resolutions, to 4k or ultrawide monitors.

For example, this is Masteroid running at Steam Deck resolution of 1200x800:
![image](https://github.com/vchelaru/FlatRedBall/assets/711100/bd26e355-7d91-4839-adad-99f6f39bfbaf)

The UI scales but starts looking empty and poorly-utilized at 1440p:
![image](https://github.com/vchelaru/FlatRedBall/assets/711100/5d7033fd-61bc-480d-91e9-5aeb3671b552)

Simply changing something like text size doesn't solve the problem of the layout having large empty spots or areas that overflow.

This problem is currently completely unsolved for cross platform games. If you build an Android game you almost have to load a completely different Gum project and have different bindings to make UI that works for both PC and Mobile.

## Proposed Solution

Many UI Frameworks have features like minimum and max width but these could be very time consuming and problematic to add. Gum already has a really robust State system. The proposed solution would emulate some of the responsive design features that exist in things like CSS, but focus on leveraging the functionality that Gum already has to minimize implementation effort.

The proposed workflow would be:

- The designer uses a behavior-like system to define an "interface" for components. This interface would add a state category such as `ScreenResolutionCategory`
- The designer would specify which states are in that category. For example, they might specify states like `Mobile`, `Tablet`, `PCLow`, `PCMedium`, `PCHigh`. The exact states and what they mean need to be game-specific as games will have different decision making. Some games could support portrait vs landscape.
- During design time, the designer adds the Responsive interface/behavior to components, which automatically brings the state category and state names defined in the behavior to a component (just like Forms controls currently work). This allows the designer to change any layout property that can be defined in a state.
- The chosen `ScreenResolutionCategory` state would always be cascaded to children while editing in Gum. For example, if you're working on a `MainMenuComponent` and you choose the `ScreenResolutionCategory.Mobile` state, it would also apply that state to children components at design time so you can preview what the layout looks like for each state.
- The runtime would have the same behavior as editing in Gum: A property should exist globally in on the Gum runtime so the developer can query the display however they see fit and then set the global state, something like `GumRenderer.CurrentScreenResolutionCategoryState = ScreenResolutionCategoryState.MobilePortrait`
- Setting the global state cascades to all children and updates the layout.

## New Features Needed

Based on the workflow above, these features would need to be added to Gum and the FRB runtime:

- [ ] Gum has a special `ScreenResolution` behavior (name debatable) that allows users to specify states
- [ ] `ScreenResolution` behavior can be added to any component, just like Forms behaviors
- [ ] Components with the `ScreenResolution` behavior have the user-defined states that represent different resolution/density layout options
- [ ] When editing a `ScreenResolutionCategory` state on a component, that state is also displayed on any child components recursively for previewing purposes
- [ ] The runtime exposes a global `CurrentScreenResolutionCategoryState` property on some core Gum service
- [ ] Setting the global state applies recursively to all children at runtime

## Problems and Unknowns

- I'm not sure how well using a state based system would work with other state things. The designer would have to be very careful not to override properties that are set in the `ScreenResolutionCategory` in other categories like Forms states
- This would be challenging to understand and use effectively as a designer. I don't know how to solve this because that's true on every platform I've used. Responsive design on the web is very challenging and numerous frameworks and tools exist to try to make it easier.

**Comment by vchelaru** [comment]
This is a huge feature, and some of the requirements may have unexpected consequences so I'm going to break these down into a few separate concepts.

## Corrections

Although the task above asks explicitly for a ScreenResolution state, this is a little restrictive and requires more one-off code than I'd like. Instead, I'd like to have the concept of a state supporting "recursive assignment". If this is true, and if it's defined on a behavior, then setting this value on an instance which implements the behavior will recursively assign it on any children which also implement it.

In code this would be a function for assigning recursively.

## Behavior Interface States

I actually thought this was already done, but maybe not. If a behavior is defined in Gum, that behavior should generate interfaces. If that behavior defines state categories with states, then those should be defined in the interface as well.

Question - what happens if a behavior defines a category and states, but the implementing component adds additional states to the category. This would result in more entries in the enum at the derived but not base.

Solution - the enum must be defined at the behavior level *and* at the component level, and the two must differ. The behavior's property will be explicitly implemented, and will mirror the non-interface enum.

## Global States

The intent with Global States is to select a state (such as MobileLayout) on the current element and to also have that display recursively to all children. 

Should this be a "global" state which can be set independent of the current component? Or should it be something you set on the current screen/component and then it recursively applies to the children.

My initial thought is that it would be set at the screen/component level. This means that if a component does not define this category, then any children inside the screen/component cannot be viewed in this mode. In other words, this means that all screens must implement the desired behavior with recursive states.

## Apply Recursively

States in behaviors need an IsAppliedRecursively property. If true, this is forced on all implementations of the behavior. Individual components and screens cannot assign or undo this value. It's a behavior-only property.

**Comment by vchelaru** [comment]
- [x] Verify that behaviors make interfaces
- [x] ~Restrict behaviors from creating interfaces if the interface is a .Forms behavior~ They already do for existing games so...since it's already implemented and isn't causing problems let's leave this alone for now.
- [x] Behaviors with categories create enumerations for those categories
- [x] Behaviors have properties for each of their behavior type
- [x] Implementing screens/components of behaviors have explicit implementations for enums, along with non-explicit 
- [x] Setting the enum explicitly should set the underlying property
- [x] Create a SetStateRecursively in GraphicalUiElement which will set the state
- [x] Add ability to mark states as IsSetRecursively only on behaviors
- [x] Setting a state that is marked as recursive in the editor at the top level will recursively set it below. What if it's set "mid" do we want to do it recursive? Not sure....

**Comment by vchelaru** [comment]
I believe this is finished. I will close this issue, although there could be bugs or additional changes needed which should go in new issues.
