### ISSUE TITLE
LayeredTileMap variable throws new errors in Glue

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#1122]
![imaxe](https://github.com/vchelaru/FlatRedBall/assets/24922404/10e8c6c4-ea6b-4708-8e6a-1b0b77a57065)

These errors started to appear on my project after updating the source. They were not present before. The LayeredTiledMap types obviously are part of the project and it even runs fine from VS and Glue after clicking yes on this dialog:

![imaxe](https://github.com/vchelaru/FlatRedBall/assets/24922404/df51b12a-feca-4fee-828e-75eb057559ae)

This is the variable reported by Glue:

![imaxe](https://github.com/vchelaru/FlatRedBall/assets/24922404/488611e9-3c58-4923-8ac0-0f1413d388e7)

**Comment by vchelaru** [comment]
This error was added recently to detect if a variable references a CSV that has been removed. In this case the code was confused because it is a tunneled variable. For now, the point of these errors is strictly CSV so I removed the check on tunneled variables.

Commit 24b4981f3024cd705c3dbe943b1cc502ce1eb403
