### ISSUE TITLE
When Adding a Shader (.fx file) to a Screen/Scene in Glue, the corresponding .xnb file is not getting produced, which causes errors

### ISSUE THREAD

**Issue by mza299** [vchelaru/FlatRedBall#121]
The following error occured when following the steps listed in the tutorial :

https://flatredball.com/documentation/tutorials/code-tutorials/graphics/flatredballxna-tutorials-custom-sprite-effects/

The Glue forms application crashed and closed down when I was doing the following:
1. Select any Screen from the the Screen drop down list in the explorer tab in Glue.
2. Drag and dropped a .fx file onto the screen
3. The following error appeared

![8t0qr6PrXv](https://user-images.githubusercontent.com/37943447/119715169-9b325300-be5b-11eb-977c-9f5371199af2.png)

4. Furthermore, I reopened the Glue without any errors and reloaded the project
5. I ran/debugged the project from visual studio
6. A System.IO.FileNotFoundExeption error occured. The error occured in the generated screen file. In my case this was GameScreen.Generated.cs
![devenv_m2xCKMt6AX](https://user-images.githubusercontent.com/37943447/119715745-3aefe100-be5c-11eb-90e8-92617e1d53f1.png)

**Comment by vchelaru** [comment]
The error is caused by not having installed MonoGame for Visual Studio (version 3.7).

Of course, Glue should not crash, and it should give a more informative error. Now it does:

4c99e972224d4eb5a4fb8027ea43aeb2c791e3ec

To solve the problem, install MonoGame 3.7:

https://community.monogame.net/t/monogame-3-7-1/11173

The next Glue version will have more informative errors.
