### ISSUE TITLE
[Gum] Cannot set arbitrary NineSlice dimensions

### ISSUE THREAD

**Issue by Arcnor** [vchelaru/FlatRedBall#1232]
Unless I'm missing something, there doesn't seem to be a way of adjusting the NineSlice "component" (might not be the right nomenclature, sorry about that)? I can see the slicing on the editor, but no way to change it.

**Comment by vchelaru** [comment]
I'm investigating now and will post updates here soon.

**Comment by vchelaru** [comment]
As discussed here:

https://flatredball.gitbook.io/gum/gum-elements/nineslice

you have a few options:

1. You can create an entire texture, and modify the texture so that it slices the way you want when it is divided into thirds on the X and Y axes.
2. You can create a portion of your image which will be displayed in the NineSlice (in a sprite sheet) and adjust the coordinates being displayed, as shown in the "Custom" section here https://flatredball.gitbook.io/gum/gum-elements/nineslice/nineslice.texture-address

I realize that neither of these are answering your questions directly, as it sounds like you would like to change the ratio of each section so they are not 1/3. 

The NineSlice does not have a built-in way to change this "1/3" slicing ratio, it is currently hard-coded into the NineSlice object. Therefore, you can do a few things to work around this:

1. You can adjust your source PNG to stretch or shrink the "inner" 1/3 of the portion that will be displayed in the NineSlice. This is the way I'd recommend doing so, since the NineSlice will stretch this anyway so there really isn't any value to having "unique" artwork in this section.
2. You can create a custom NineSlice object, as shown here https://flatredball.gitbook.io/gum/examples/custom-nineslice . While this solution may work for you, and gives you more freedom on texture coordinate selection, this does introduce some potential limitations, such as the behavior of the middle sprites if you shrink the NineSlice too much.

Please let me know if any of these options work, or if your situation is such that having the ability to slice up the sprites using something other than a 1/3 ratio is necessary and perhaps we can come up with other solutions.

Feel free to reply here, or to ask in Discord. I will keep this issue open for discussion until we come up with a solution.

**Comment by Arcnor** [comment]
Thank you so much for the investigation and explanation.

I want to use Gum to replace an existing system I have, but I do not want to recreate all the content.

I'm fine adding the functionality myself, but I'll need some guidance there. I've checked the source and it seems that internally the calculation happens on every draw, so from my limited understanding, adding fields in the editor to replace this ratio (plus saving it to the project file of course) should be enough?

Anyway, thanks again. I'll open some other issues later about other issues I've found.

**Comment by vchelaru** [comment]
That makes a lot of sense, and now I understand why you need to have different ratios for rendering. I can definitely add support for this in the Gum tool. Can you give me an idea of how high-priority this issue might be so I know when to start working on it?

**Comment by Arcnor** [comment]
As generous as it sounds that you're taking my priorities into account, I'd never expect you to do so at all! Especially as a newcomer to the project, but again, much appreciated 😄.

I'll just quickly hack something in the meantime, and will definitely test or collaborate if you want when you can get it into your current stream of work.

Thanks again!

**Comment by vchelaru** [comment]
I've already started on it :)

Are you using prebuilt binaries for Gum and your game? If you already are using source, or if you want to switch to that, I think I should have something to test this morning.

**Comment by Arcnor** [comment]
Well, that's definitely awesome!

I'm using source, been trying to fix a few annoyances on my own (will open a PR if I manage to do so). I don't have integration with my game yet, and haven't even looked at the API side of things, but first I need to be able to build the UI, no point in trying to integrate yet :).

**Comment by vchelaru** [comment]
Yes, please do open issues or PRs. As I mentioned before, the FRB community is very active on Discord as well so if you have any questions you can join there and get a quick response. https://discord.gg/tG5RBgw

**Comment by vchelaru** [comment]
Alright, this has been fixed! I pushed to Gum here 439bd63339d93d08a99a2b2a0b14ad20b5d0ac3a

There are no changes to the FlatRedBall repository for this, but you will need to rebuild Gum locally to get access to this property. Please let me know if you need anything else.

**Comment by Arcnor** [comment]
Thank you very much, that was very quick! I really appreciate it, and it seems to work great! I might need to change it in the future so a height also can be specified, or even the standard left/top/right/bottom instead of a single unit, but for now my quick tests are all using a single ratio for all sides, so this works fine, thanks again!
