### ISSUE TITLE
[Gum] Boolean exposed variables have incorrect default value

### ISSUE THREAD

**Issue by Arcnor** [vchelaru/FlatRedBall#1237]
1. Create a component `BaseComp`
2. Add a `Text` object, expose its `Visible` property as `LabelVisible`, or `UseFontSmoothing`, or any other `bool` variable that defaults to `true`.
3. Check `BaseComp`'s exposed variables, they will be `false`.
4. Use `BaseComp` anywhere and try to make the `Text` invisible, you'll have to set `LabelVisible` to `true` (nothing will change) then set it `false` again, label will disappear in this case.

**Comment by vchelaru** [comment]
Confirmed bug on step 3:

![image](https://github.com/vchelaru/FlatRedBall/assets/729631/665601dc-f814-4105-9f80-675cdd2fa34a)

**Comment by vchelaru** [comment]
# 3 Fixed in BaseComp display (when viewing the component)

![image](https://github.com/vchelaru/FlatRedBall/assets/729631/ffaff56e-b78b-45d0-acaa-085a42878e55)

# 4 Also fixed when viewing an instance of the component

![image](https://github.com/vchelaru/FlatRedBall/assets/729631/a7714e15-85a2-4401-9ab6-5ecb7e4dd790)

In Gum commit 6b6bad9a140291c5573f12e340840c5b32b02616
