### ISSUE TITLE
Screen reload on TMX change loads previous change, instead of the latest, after one reload

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#1417]
See repro video:
https://github.com/vchelaru/FlatRedBall/assets/24922404/0cf3887c-15f2-42ea-8918-a78acc318424

**Comment by vchelaru** [comment]
This actually could be restulting from the tasks processing more quickly than before, so the TMX hasn't had a chance to finish copying.

Need to increase the time from 600 ms to a larger value, or perhaps to even make it tunable in the UI.

**Comment by vchelaru** [comment]
See

https://stackoverflow.com/questions/1304/how-to-check-for-file-lock/20623302#20623302

**Comment by vchelaru** [comment]
I believe this has been fixed. 

Previously, the restart command was waiting a flat 600 milliseconds to wait for tasks to be finished. This started failing due to recent optimizations to only copy the file one time even if it changes on disk multiple times. Therefore, this fix has 2 changes:

1. Look at the tasks that are queued up. If the file's copy task is still in queue, wait. This makes the restart command far more reliable. https://github.com/vchelaru/FlatRedBall/commit/d23ab2d286c31398cb07ec2f53b7488995d571bc
2. If the game is running, give copy commands very high priority they copy immediately. This may result in multiple copy commands in some rare cases, but it's a tradeoff that prioritizes the user's wait time to see content appear in-game.  https://github.com/vchelaru/FlatRedBall/commit/aa33d327e0370f9900b99ac0ff5c899353b03b17

**Comment by mfigueirido** [comment]
Fix confirmed! Closing this.
