### ISSUE TITLE
Glue Forms rendering should not be broken

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#151]
This started within the last month or so. Glue has rendering problems for Forms (I assume) components. This used to affect the animation editor and Gum. Adding this code in `Program.Main` before application startup fixed the issue in the Animation Editor and Gum but, to be honest, I don't really know how or why. I stole the fix from an SO question a long time ago but it would be nice to understand the consequences of this line of code and why the issues started before blindly fixing:

```
System.Windows.Media.RenderOptions.ProcessRenderMode = System.Windows.Interop.RenderMode.SoftwareOnly;
```

Gif:
![render-fail](https://user-images.githubusercontent.com/711100/128097350-9668f638-d1db-41aa-bdc7-f6f310556077.gif)

**Comment by vchelaru** [comment]
All of the controls you are looking at are actually WPF controls, and WPF uses DirectX under the hood (afaik). It seems like sometimes DirectX doesn't like this, and forcing it to use software will probably improve stability at the cost of performance. 

@profexorgeek since I cannot reproduce this problem on my end, do you want to see if that line fixes it on your end assuming you are building from source?

**Comment by profexorgeek** [comment]
Tested and confirmed that it does fix it. This could potentially be a config setting in Glue somewhere so rendering perf isn't sacrificed on systems that have no problems.

For now I'll commit the fix with a comment and let you determine whether to wrap it in a UI setting somewhere...
