### ISSUE TITLE
User should not be able to right-click between elements to produce an empty context menu

### ISSUE THREAD

**Issue by vchelaru** [vchelaru/FlatRedBall#1522]
A right click between items should not show a context menu at all. Currently it is possible to click between tree items and get an empty context menu.

![30_06 02 24](https://github.com/user-attachments/assets/0ae21e1f-d358-4273-b268-dcf42db56b4a)

**Comment by vicdotexe** [comment]
@vchelaru 
This is a result of the odd implementation of your contexts menus:
![image](https://github.com/user-attachments/assets/10c16afb-b3bc-451d-903f-03f0a9986ccf)

It appears there is a single context menu living on `TreeListBox` control itself. The code-behind is doing some crazy stuff to give the illusion of the context menu living on the menu items... 
What you're seeing is actually expected behavior: by hitting that sweet spot between the menu items you're still clicking on the control where the context menu lives, and with how it's been set up in code behind, that just makes for an empty menu, you can see it clearly if you click the empty space below the tree items.

You can see it exists in the previous release:
![image](https://github.com/user-attachments/assets/0d8d8c20-404d-47d0-bd98-c9e0e2d0bcc1)

Off the top of my head there's not really a simple fix for this, just kind of exposes that the whole system needs to be re-implemented correctly. I'll sit on it for a bit and see if I can come up with anything clever in the meantime, but in the end it will just be a bandaid.

**Comment by vchelaru** [comment]
Thanks for the update on this. If it's a tougher fix, we can def hold off on it. If there are things I can do to start on a re-implementation of this, I'd like to hear more info about it. Maybe we'll continue the conversation in Discord...
