### ISSUE TITLE
Code quality issues

### ISSUE THREAD

**Issue by Lucasharskamp** [vchelaru/FlatRedBall#1527]
Hello,

Just writing down some issues relating to code quality, for sake of maintainability. If plan is approved, I hope to make a series of small PR's to alleviate some of these issues. This would make improving the engine and preventing bugs easier through small QoL updates.

1. FRB doesn't have a code standards file, or a simple reference to the Microsoft C# Code Conventions, to allow for standardization across the project. [Microsoft Docs: Common C# code conventions](https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/coding-conventions) 

Currently, there are no code standards, causing code to follow multiple styles at once, ruining readability. Example:
![image](https://github.com/user-attachments/assets/807f0a9a-0b24-4432-92b2-58a5bffc57f5)

- The field _parameters_ hides the local variable
- references to properties/fields in the class use both _this._ and direct reference
- Type assignment for the int variable, even though it is clear what the type will be. (see MS Docs link above)
- No XML summary for the method.

**Proposed solution**: Set up an agreed upon code standard, or simply use the one MS provides (since corporations often also use it, making it easier for professional developers rather than using a custom style). Then, add resharper/VS instruction files so Intellisense uses it properly. Also, perhaps it is to be taken into consideration not to allow fields in classes (only for structs), and instead use private properties.

2. Many methods, classes, interfaces, fields and properties, whether private/protected/internal/public, lack XML summaries. XML summaries help for 3 reasons:
- When hovering, it shows the documentation
- Helps for auto-generated documentation
- When using AI tools like GitHub Co-pilot, it provides the probability machine better instructions to use the existing code base, providing better options to both engine developers and end users.

**Proposed solution**: Enable for all projects that XML documentation will be exported and that warnings be given out for lacking entries, then ensure those entries are taken care of bit-by-bit.

3. There are ton of ''obsolete'' warnings, warning that the engine is using its own deprecated features. Those need to be replaced with their replacements one-by-one.
4. Many fields, properties and temporarily variables (are assigned and) remain unused. This is sometimes because these variables are used within a certain build scope (#if NET6_0, etc) and therefore should only exist within their scope. Same goes for _using_ statements. 
5. Certain Tasks are not awaited, causing potential thread issues.
6. Float equality operators shouldn't use ==, but instead use the proposed solution by MS, see [Float.Equals documentation under 'Remarks'](https://learn.microsoft.com/en-us/dotnet/api/system.single.equals). Consider what the threshold should be for equality.
7.  Exception throwing for improper parameters happens during #debug, but often not in production. Is this wise?

**Proposed solution**: work through these issues on a per-project basis. To start with the codegenerator, to ''improve'' a small number of files in GlueFormsCore.

**Comment by vicdotexe** [comment]
@Lucasharskamp 
> Type assignment for the int variable, even though it is clear what the type will be. (see MS Docs link above)

I don't think explicit type declarations should be considered wrong even if they can be inferred. Those docs are saying prefer to use a signed type, but it's ok to use `var` when the the type can be easily inferred. What benefits come from forcing usage of `var` over `int` in that screenshot? My vote is prefer explicit declaration, allow usage of `var` but suggest explicit.

**Comment by vchelaru** [comment]
I have updated the refactoring guidelines here:

https://docs.flatredball.com/flatredball/contributing/contributing-code-pull-requests

Please read through this if you do intend to make any changes. The most important point here is that any refactoring done without context obtained from feature work or bug fixes will likely not be approved - they've caused too many problems in the past.

I appreciate the fact that these changes are intended to make the code base cleaner and more inviting to users - I agree with this as well, but the way we get there must be done in a way that does not add a burden to existing maintainers, and in a way that does not introduce bugs. Unfortunately, previous refactors have done both.

> FRB doesn't have a code standards file

I believe the code standards problem has been solved with a previous PR.

> No XML summary for the method.

Do not add any XML documentation unless the context is perfectly understood, including gotchas and common usage. Documentation which reflects the obvious (method names, parameter names) do not add any benefit to the project. They simply restate what is already know. They can be frustrating to users who are expecting clarification or additional information. I encounter this daily when working with Maui. I'd rather have no XML summary than something which has no value add. This keeps the noise to a minimum.

> Enable for all projects that XML documentation will be exported and that warnings be given out for lacking entries, then ensure those entries are taken care of bit-by-bit.

As was discussed in discord, it is impractical to provide xml documentation for all public members, and in some cases they are just added noise. Warnings should not be added for missing xml documentation since no one will ever address them all (I've even tried!) and the xml warnings hide other warnings.

I'm closing this issue since there is no clear way to complete this as defined. Individual fixes can be made going forward, but they must follow the guidelines outlined in the contributing section linked above.
