### ISSUE TITLE
Glue should not generate code that creates CS0108 member hiding warnings

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#1533]
When generating Gum runtimes, Glue generates code that triggers CS0108 warnings at compile time. In most cases, this warning is for the `VariableState` enum and the associated `CurrentVariableState` property for gum components that inherit.

We likely will need to create a new .gluj version and stop generating this into inherited objects since adding states without a category is no longer allowed in the Gum UI.

Example screenshot of warnings:
![image](https://github.com/user-attachments/assets/0211ef04-739a-4fe2-84b4-c1a8b324b34c)

**Comment by vchelaru** [comment]
VariableState enum and CurrentVariableState are both code generated for uncategorized states - or the potential for uncatgorized states. They are always generated to minimize the need for code to be refactored when all states have been removed. 

However, uncategorized states have ambiguous variable membership which categories solve. Both Gum and Glue require states to be categorized in the UI, but codegen continues to generate uncategorized states so that old projects to not break.

I believe the solution here is to stop generating uncategorized states, but this would break old projects. Therefore, we need to increment the GlueProjectSave version, document the new version increase, and explicitly warn that if you upgrade to this version, you will lose this codegen - just in case you are depending on it.

**Comment by vchelaru** [comment]
fixed by 9e40321700ab0e40808bf5317738541dd36999b2
