### ISSUE TITLE
Effect wrapper isn't removed when the user removes the corresponding .fx file

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#1585]
Steps:

- Go to Global Content Files and add a prebuilt effect file: 
![imaxe](https://github.com/user-attachments/assets/dfb2ff17-64a4-442f-a8d8-67593e84438a)

- Remove the effect file (.fx) from content.
- Observe the effect wrapper is still present:
![imaxe](https://github.com/user-attachments/assets/890a62ce-dc9c-4832-85b5-3b7e63ed7ff9)

**Comment by mfigueirido** [comment]
Regardless of the deleting problem, it appears that effect wrapper's code isn't updated after changing the engine's source file as well.

**Comment by vchelaru** [comment]
The current effect system does not keep the files synced to the engine, the way a normal Generated file is synced. Rather, it creates a "copy" so that the user can make edits. This is especially important for the "Example Gradient" but it can be useful for others if a user needs to customize the shaders in the future.

This may change in the future, but for now I'd like to keep it as flexible as possible without forcefully overwriting the user's changes on these effects when Glue re-opens.

**Comment by vchelaru** [comment]
Fixed by a3bf43c2f6dcc4b6b2f65f91764b19aae9ff1b5f
