### ISSUE TITLE
Default panel for selected node still not showing when it should

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#1593]
Note how clicking the variables node from a bookmark does not bring the variables panel into view.

https://github.com/user-attachments/assets/53fcc998-3a06-41ca-8b2a-9279f81c2784

This seems to happen after the user explicitly changes the current panel by clicking on it. After that, the default panel functionality does not seem to work anymore.

**Comment by vchelaru** [comment]
This is happening because Glue remembers the last node you clicked for each type of node (such as Variables) and attempts to show that. This causes confusion and I've also been frustrated with this behavior. We discussed it briefly here:

https://discord.com/channels/586997072373481494/1280582538196418560/1299745034941366343

For now we're going to remove the behavior of remembering the last tab clicked, see if it solves the problem, and consider some kind of option for selecting the selected tab.
