### ISSUE TITLE
SoundEffectInstance without backing file

### ISSUE THREAD

**Issue by RychuP** [vchelaru/FlatRedBall#1621]
It is possible to add SoundEffectInstance to an Entity via QuickActions/Add Object which results in invalid code generation.

**Comment by vchelaru** [comment]
Thanks for reporting this. As I see it, the biggest issue here is that you can add a new SoundEffectInstance, then get an error in your project. It's not clear if you are getting an error because of a bug in FlatRedBall, or if you did something wrong. If you did do something wrong, what? And how do you fix it?

To to solve this, I've added more error checking logic in FRB so that you will be told what is wrong:

![image](https://github.com/user-attachments/assets/4422ac21-7da6-4cab-9623-0edd22a3ab59)

This has been fixed here:

1ab64e98b768d9bbb5d311cc3aae66d9b66c7fe9
