### ISSUE TITLE
Need 4 action images for wizard "quick" setup

### ISSUE THREAD

**Issue by vchelaru** [vchelaru/FlatRedBall#235]
Here's the current page:

![image](https://user-images.githubusercontent.com/729631/137814389-075de364-5205-4665-9370-8a590ae76026.png)

I would like to have 4 options:

* Standard Platformer
* Standard Top Down
* FlatRedBall Forms application (a new type)
* Custom (Advanced)

All 4 will need unique action images in the pastel/flat/rounded corner style of the other icons.

**Comment by profexorgeek** [comment]
Some clarifications:

1. What size do you need these icons (where will they be used)?
2. Do you also need a new card-sized icon like the above?
3. Do you plan to eventually move to a dark theme like the mock we kicked around a while ago?
4. Do you have a list of every icon and image needed in Glue? Having this inventory would be super useful because I could create icons for all of the new build tools, the existing buttons, and these quick-action things at once with a matching style!

**Comment by vchelaru** [comment]
1. What size - this is hard to say exactly because when they appear on different DPI devices, they can be drawn larger. The screenshot above is the "native size" when they appear on a desktop with no scaling, but the actual PNGs are stored in `FlatRedBall\FRBDK\Glue\OfficialPlugins\QuickActionPlugin\Icons` so you can compare there. Note there is an "Original" folder for higher-res images.
2. Yes, that is where the images will be used.
3. Yes, although when that happens we'll prob need to do a pass on all action images at once. You don't have to think about this now if you don't want to.
4. I don't but you can see them all in the folder listed above.
