### ISSUE TITLE
Icon needs

### ISSUE THREAD

**Issue by vchelaru** [vchelaru/FlatRedBall#253]
@profexorgeek 

I don't know if this should be closed, or updated when icons are added.

* Clear (X) Icon to click when to clear out the search box in the tree view window.
* Icon to collapse all nodes, similar to the collapse all in Visual Studio solution explorer

**Comment by profexorgeek** [comment]
Let's just add new tasks as you have groups of icons and close the task out when the icons are complete. That's easier for me to do in batches and associate w/ a commit.

Fixed in: https://github.com/flatredball/FlatRedBallMedia/commit/288f0e2c480283d769708c961310afceb9de4532

![image](https://user-images.githubusercontent.com/711100/142732680-2b25d1c7-924e-49c4-a033-f355ffcff2ac.png)
