### ISSUE TITLE
More Glue Icons are needed

### ISSUE THREAD

**Issue by vchelaru** [vchelaru/FlatRedBall#278]
For @profexorgeek 

- **Build button** Used to build (but not run) the game. This is normally hidden but users can click it to build in Glue without running to see if there are errors. 
![image](https://user-images.githubusercontent.com/729631/144453320-d47c1aec-2d3c-4fa7-af28-101a56eca396.png)
- **Pause Button** Used to pause the game when it is running. The mock includes this button, but there is no PNG for it in the FlatRedBallMedia/EditorGraphics folder. 
![image](https://user-images.githubusercontent.com/729631/144453695-1f7661c4-60ab-48c9-8793-677886764a31.png)
- **Unpause Button** Used to unpause the game when the user has paused it. Maybe this could be the same icon as the play button? But I don't know if that's confusing since it may sit right next to the "play vs edit" buttons. Perhaps if it's the same icon, but a blue color like the pause? Not sure... 
![image](https://user-images.githubusercontent.com/729631/144454168-71412034-6bf2-43d1-b88f-d4a608cd02d3.png)
- **Advance One Frame** Used to move the game forward one frame when paused. Allows debugging where precise movement/positioning is needed, and allows animations and particles to be seen one-frame-at-a-time.
![image](https://user-images.githubusercontent.com/729631/144454431-849d5db5-0d63-431e-b7e6-9e7e76f189c6.png)

**Comment by profexorgeek** [comment]
Okay, I did a bit of research on what tools like Premier, VLC, and other media editors use for icons. Here's the pattern I think we should use to be "spiritually consistent" with other usages of these icons:

![image](https://user-images.githubusercontent.com/711100/144456603-f31fedff-5a51-4236-a7ab-09705850ab96.png)
This means "go to start" in video media. In FRB this should be the "rebuild everything" button. This is a change from the existing icon but should be made because of the info below...

![image](https://user-images.githubusercontent.com/711100/144456743-5f78eda2-1b53-4a36-825c-eded625310e6.png) ![image](https://user-images.githubusercontent.com/711100/144457736-d605c2f9-e118-4745-a88f-46cc9a4c3142.png) 
These can mean step forward/back one frame OR they can mean step forward/back one clip/chapter/unit, depending on the application. Some programs put the bar on the wide side of the directional arrow as shown below but Font Awesome does not have an icon for this.
![image](https://user-images.githubusercontent.com/711100/144458093-3e1a5587-a238-4909-9d0e-e3eebc970238.png)
I think we should use the forward icon to mean "step forward" but I don't see any relevant use for the reverse one.

![image](https://user-images.githubusercontent.com/711100/144457090-0e37b8d5-f0ec-4d9f-985d-d19879b9f2af.png) ![image](https://user-images.githubusercontent.com/711100/144457317-e31ccc36-6b47-4a38-bb2a-ef2b5e213c93.png)
This means "rewind" and "fast forward" but many applications, such as Netflix, allow multiple clicks to change the specific rewind speed. This might make sense to use for changing the time factor.

![image](https://user-images.githubusercontent.com/711100/144457466-5818bf22-d2b8-43c1-8ae2-d823ca57befc.png) Play, Pause, and Stop are well known. We should use this play icon for play/pause as it is visually distinct from the play icon that means "build and run".

![image](https://user-images.githubusercontent.com/711100/144457629-67aada80-e01c-4ae0-8ee1-1e3125976003.png)This means "go to end" and I can't think of any valid meaning for this in FRB.

**Comment by vchelaru** [comment]
Yes, I like it. I think based on what you posted above, we need the following icons added/redone:

* Go to start - rebuild everything and restart
* Step forward - move forward one frame
* Play/stop/pause We already have a stop icon so if that's okay, we need play and pause.
* Build - this wasn't mentioned in your post above, but it is mentioned in the original, and it doesn't really follow the movie control theme

**Comment by profexorgeek** [comment]
Pushed. A couple notes:
- I didn't update the mock, this is pretty time consuming so let me know if you can wing it on the new icons. Try to group like functionality
- The original "icon_play" was renamed to "icon_run" which is a similar button but different use case
- While your build icon is similar to Visual Studio, I think a hammer is a more intuitive expression of "build" and ties in to the wrench metaphor for edit. JetBrains uses a hammer.
