### ISSUE TITLE
Deleting screens leaves generated files behind

### ISSUE THREAD

**Issue by Freestyle00** [vchelaru/FlatRedBall#296]
Deleting screens in Glue will still leave the generated files behind.

Reproduction
Step 1:
Create a game
![GlueFormsCore_QLKQ3GbcKR](https://user-images.githubusercontent.com/69159664/147127579-d3dd2c6c-1f90-4330-bb00-dfe6e90d172d.png)

Step 2:
Decide you dont need the two generated levels as you only need Gamescreen
![GlueFormsCore_fyrTAIKwsS](https://user-images.githubusercontent.com/69159664/147127562-5e207b18-7641-471a-b755-90c516493ebc.png)

Step 3:
Click Remove and delete the files 
![2bZVJS9dvq](https://user-images.githubusercontent.com/69159664/147127706-3c82d000-2a91-4686-a6f3-a3a993f8b440.png)
:

Step 4:
Bunch of errors are popping out because the files are still there
![bfUIHzbR6K](https://user-images.githubusercontent.com/69159664/147127767-74b44db9-9c5a-4f15-a0e5-857142482886.png)

![vzr7xOWeth](https://user-images.githubusercontent.com/69159664/147127826-bec9d261-5e4a-4e3b-bd70-61daa138dc36.png)
:

(Deleting the files also removes the errors)

Additional notes:
This also happens when creating levels by hand and deleting them

Same goes for entities too

And it leaves the Gumforms behind too

Deleting the screens in Gum solves the Gumforms issue

**Comment by vchelaru** [comment]
This fix was made in 2 releases. The first is for a Glue bug which didn't delete the .generated.cs files. This happened due to the tasks re-generating code for an already-deleted screen. It's been fixed by awaiting tasks.

5064cec4c7f4b191be2f7bf46507fc04d8cc1ad7

The second fix was for the Gum plugin to ask whether you want to delete the Gum screen.

eac0082a9b2d71fad4521874a235bc1ff9188c6b
