### ISSUE TITLE
Enhacement for GlueView - Display Cursor Position

### ISSUE THREAD

**Issue by Freestyle00** [vchelaru/FlatRedBall#299]
Right now the GlueView screen is just your game inside glue.

This is nice but how about it gets better, my idea would be to add a coordinate display like when you hover your mouse over something the cooordinates of where your mouse is gets displayed like in this screenshot I did in 10 seconds.

![GlueFormsCore_XtgekTD1gq](https://user-images.githubusercontent.com/69159664/147296503-3df58639-5bb8-437d-8557-a21f70ea2107.png)

**Comment by vchelaru** [comment]
Since the game is a separate executable than Glue, the only way for Glue to know this information is to ask the game for the cursor at a high frequency. While this is certainly possible, it's a heavy system to add for something which may not be useful in a lot of cases. Instead, I think it's best to document how to use the EditorVisuals object in a tutorial.

**Comment by vchelaru** [comment]
I've added documentation here:
https://flatredball.com/documentation/api/gluecontrol/editing/editorvisuals/


![24_11 54 34](https://user-images.githubusercontent.com/729631/147369547-bbe93ec4-a858-4583-9868-1ff5754013e2.gif)

At some point Glue may display more information in edit mode, but I don't want to add just the cursor in yet unless I know I'll need other information too. This should help for now.
