### ISSUE TITLE
Changing the entities or screens to much in GlueView will at some point crash everything

### ISSUE THREAD

**Issue by Freestyle00** [vchelaru/FlatRedBall#300]
as you can see in these steps I did the game crashed after some time of switching around 

Also there is the thing that the edit mode just disabled itself when going from GameScreen to level screen
![qwsH3gRM9w](https://user-images.githubusercontent.com/69159664/147299431-5d9bcf4e-a36d-4271-83b2-5e00d7e2a8d3.gif)

**Comment by vchelaru** [comment]
I believe this has multiple problems. The first problem is:

When the user selects the GameScreen, the game shuts down. This is likely because the GameScreen is an `abstract` class, so the game should do its best to select a suitable screen. Perhaps it should select the first screen (alphabetically?) that inherits from abstracts? 

To reproduce:

1. Start the game on any level
2. Go into edit mode
3. Select an entity
4. Select GameScreen

Observe - game shuts down
Expected - Level1 (or some base screen)

**Comment by vchelaru** [comment]
I believe that the fix for the issue listed above, plus a few other fixes to the latest editor, have fixed many of the issues
![27_15 23 55](https://user-images.githubusercontent.com/729631/147510956-06fff5a2-858d-4fcf-b864-d1e5e6d51be4.gif)
