### ISSUE TITLE
Add support for wildcard Files

### ISSUE THREAD

**Issue by vchelaru** [vchelaru/FlatRedBall#337]
Currently whenever a new file is added to the file system, Glue requires that the file is also added to Glue. Glue already understands how to work with most files without any configuration because the user can drag+drop the file into the folder.

Glue functions based on objects called ReferencedFileSaves (RFS's). These must still ultimately exist in the .glux file one way or another, because otherwise most of Glue would break. However, the creation of these RFS's should be automatic. 

The functionality would be to add all files (which have not been explicitly excluded as explained before) whenever:
* Glue loads
* A new file change is detected

Glue would need some kind of logic to determine which files should be included or excluded. Should there be a whitelist? Plugins should be able to modify this. Actually, there is FileCommands.IsContent, but that uses PluginManager.CanFileReferenceContent....although ATIs will do the trick for files which are themselves content but cannot reference content, so I think we have a solution for that.

## Questions

1. What if the user has a file that is on disk, but the user does not want this file added to the Glue project? Vic doesn't think that it is a good idea to force the user to delete the file. Instead, we could have an exclude list just like Visual Studio .csproj files which Glue will use to ignore certain files. 
2. What happens if a user accidentally deletes a file on disk and checks it in. Currently the RFS in Glue will stick around, and this warns the user "OH NO, you're missing something important!". If Glue deletes RFS's whenever the matching file is missing from disk, then that could result in silent errors. Sure, a file may be referenced by an object, and in that case an error would show up in Glue, but if the file is referenced in code or dynamically loaded that could cause problems.
One solution is to add explicitly-added files, but this causes its own set of problems. Usually, users will ignore this setting and not understand it. This means that effectively all files will be added implicitly, and then they'll also be removed implicitly.
Another option is to have missing files show up as errors. This means that Glue will always implicitly add, but files must be explicitly removed. But what about temp files? An exclude list could help address this, but is it enough? This feels like it could become a management headache....
3. If a file like a PNG is added to global content (the default?), that file cannot be referenced by objects in screens or entities unless that file is also added under the Files for that Screen/Entity. This is how Glue currently works. One solution is to auto-add to all screens and entities. Nope, not going to do this, especially if we have explicit removals. Another option is to allow objects in screens/entities to reference files in Global Content Files. However, that means that file references will require qualification. This introduces a ton of work which spreads all over, including property grid, code generation, live editing, error window.....it is not fun :(
4. How should old glue projects behave? We don't want to all of a sudden add a ton of content which may be on disk unless the user selects the option to do an "opt-out" system...or maybe it should be based on .gluj version? New .gluj could auto opt in...

Vic's biggest concern is the issue of referencing files from Global Content. However, is that enough to prevent the creation of this? 

Need to talk to @profexorgeek  about the use case to see if the Global Content reference is a big deal.

**Comment by profexorgeek** [comment]
Here were some points I made in chat on the Discord server. These are key user stories related to the content pipeline. These are focused on experience versus implementation:

1. As an artist, I should be able to structure content in directories however I want. I work directly on content via external tools and so my workflow and preferences should not be subject to "how FRB works".
2. As a [normal FRB] dev, I should be confident that my content exists (is loaded into the engine) when and where I need it.
3. As a dev, I should not  be forced to think about the content pipeline and how content is loaded and unloaded unless I specifically choose to think about it for specific performance scenarios.

**Comment by mfigueirido** [comment]
To add a little bit of feedback on this topic I'll tell how content is setup on our game:

Screens: TMX files and other pngs loaded separately from Tiled.
Global Content: music, SFX, fonts, misc stuff like special effects.

If we take a look at our GlobalContent folder it looks like this:
![imaxe](https://user-images.githubusercontent.com/24922404/165975029-ef557f86-7c0f-4c40-8b7f-042eda44b404.png)

And this is how it looks in FRB Editor:
![imaxe](https://user-images.githubusercontent.com/24922404/165975190-1354e579-5040-4c0a-ae35-bd5e6ce7b007.png)

Notice how all files present in the folder are added to FRB with the sole exception of font pngs because they are considered part of the font itsef. This is true for subfolders as well because they contain music or SFX files and are all always added. If FRB was smart enough to add all those files automatically it would save the developer the tedius job of adding files each time and thus speed up development time and ease frustration. Obviously this is not so simple because content may be laid out differently on other projects.

Instead of having a fixed structure like we have now, a solution I think would be to enable the user to create "synced content folders". So the user would go to a tree node called "content" and create a new "synced folder" and there he could set if the synced folder's content is global or select the entity or screen it should be loaded with. This way he could lay out the file system the way he sees fit. On top of this he should be able to set if the folder auto-adds content automatically and which kind of content. This would solve two problems: the rigidiness of the actual system and the lack of auto-adding files.

Please note that this comment is made from a pure user experience point of view. I don't know how hard would be to code such a system in current FRB.

**Comment by vchelaru** [comment]
## Design Update

After thinking about the issues listed above, I have decided to follow how Visual Studio performs file adding. At the file level (json file for glue project or screen/entity), referenced files can be added using wildcards.

## Json Format

A typical file in JSON looks like this:

```
    {
      "Name": "GlobalContent/TextureFile.png",
      "IsSharedStatic": true,
      "DestroyOnUnload": false,
      "HasPublicProperty": true,
      "ProjectsToExcludeFrom": []
    }
```

If we want to support a wildcard, such as all files in the global content directory proper (not recurisvely) the file might be:

```
    {
      "Name": "GlobalContent/*",
      "IsSharedStatic": true,
      "DestroyOnUnload": false,
      "HasPublicProperty": true,
      "ProjectsToExcludeFrom": []
    }
```

Notice the only difference is the Name property, which indicates that all files in the GlobalContent directory should be added and should use the other properties. This allows the adding of files with custom properties. For example, the HasPublicProperty value could be modified to `false` which would result in all files in the GlobalContent directory without public properties:

```
    {
      "Name": "GlobalContent/*",
      "IsSharedStatic": true,
      "DestroyOnUnload": false,
      "HasPublicProperty": false,
      "ProjectsToExcludeFrom": []
    }
```

Following the same format as .csproj files, files can be recursively be added:

```
    {
      "Name": "GlobalContent/**",
      ...
    }
```

Additionally, wildcards can be combined to support specific types of files:

```
      "Name": "GlobalContent/**/*.png",
```

Or files with a prefix:

```
      "Name": "GlobalContent/**/TextureFiles*.*",
```

## Glue ReferencedFileSave handling

### Loading

When a project is loaded, the following steps are performed:

1. Find all ReferencedFileSaves with wildcards (*)
2. Remove all of these files from the main list
3. Loop through each RFS with wildcards and look at the file system for existing files
4. For each file match, create a new RFS which is a clone of the wildcard rfs so it inherits all of its properties except it has an explicit name.
5. Tag this RFS's IsCreatedByWildcard= true
6. Add this RFS to the main project'
7. Add the full wildcard RFS to a RfsWildcards list in the main Glue project (or element if it is in an element). 

At this point, the glue project has all RFSs filled in the list, and aside from that value being set, the RFS's will appear as if they are normal RFS's in the tree view. See below for differences.

### Editing Wildcard RFS's

Once a wildcard pattern is expanded into individual RFS's, the individual RFS's have some differences from normal RFS's. These differences are:

* The RFS will have a IsCreatedByWildcard set to true in its properties. This only shows for RFS's which are set to true for now (in the future this may show up for RFSs which match wildcards, but which are not wildcard values...
* If the user sets IsCreatedByWildcard to false, then the RFS becomes a "full" RFS as if it was explicitly added.
* All other properties on the RFS including name are disabled. The user cannot change the individual properties because these properties are inherited from the wildcard pattern. Setting IsCreatedByWildcard to true will make those properties ediatable.
* Wildcard RFS's cannot be dragged into other elements or into global content - doing so would create an explicitly-added RFS which shares files with wildcard RFSs and changing the wildcard would not change the explicitly created. This could create confusion.
* Individual wildcard files cannot be removed from Glue. They must be deleted, or the path must be modified to exclude them (this may change later)

Wildcard RFS's do have the following similarities with normal RFS's:

* They do show up in Glue (should they have a different icon indicating they are from a wildcard?)
* They do codegen like normal following all of their properties.
* Objects can still reference wildcard RFS's.
* Wildcard RFSs will participate in the dependency tracking. They can satisfy missing references, and they can cause missing references if they reference a file that doesn't exist. Actually, this is already a problem because it creates copies so...why would this introduce more? I think we should continue to allow dragging. If it is dragged, though, the IsCreatedByWildcard should get set to false.

### File Change Handling

Whenever a file changes on disk, the following logic needs to happen:

* Is any wildcard rfs referencing this? If so, was the file removed? If so, remove the RFS from the glue project
* Is the file part of a wildcard pattern but isn't referenced? If so, add it.

## Saving

Whenever a Glue project is saved, it will tie in to the logic that already saves JSON files with external references. If using external references, the logic already removes all elements and replaces them with references. Therefore, the following logic would similarly be run:

1. Remove any wildcard RFS's from the project
2. Copy all wildcards back to the main projects files
3. Save the copy

**Comment by mfigueirido** [comment]
I'm a bit confused of what will happen if I add a wildcard pointing inside Global Content. The expected behaviour would be these files to fully work like Global Content meaning they will have a codegen public property accesible from GlobalContent and unloaded when Global Content is unloaded.

For wildcards outside Global Content I just expect them to simply to be available as regular VS studio files although extra codegen wouldn't hurt.

As a side note -because it's related to this issue- allowing files with the same name on different folders would be something that would need to be supported as we talked on Discord.

**Comment by vchelaru** [comment]
> I'm a bit confused of what will happen if I add a wildcard pointing inside Global Content. The expected behaviour would be these files to fully work like Global Content meaning they will have a codegen public property accesible from GlobalContent and unloaded when Global Content is unloaded.

This is exactly what would happen.

> For wildcards outside Global Content I just expect them to simply to be available as regular VS studio files although extra codegen wouldn't hurt.

Actually they will also fully codegen and be accessible through the GlobalContent object in code.

> As a side note -because it's related to this issue- allowing files with the same name on different folders would be something that would need to be supported as we talked on Discord.

Yes, this will be added; however, since these files will basically be identical to explicitly added files, the same restrictions will apply. This means that I can initially add wildcard support, and then separately address the same-name issue.

**Comment by mfigueirido** [comment]
Sounds good. I guess the Global Content folder no longer will be the root folder to show the files in Glue. In fact being able to add global files from anywhere makes it kinda irrelevant.

**Comment by vchelaru** [comment]
Additional functionality needed to mark this as ready for beta:

- [x] Handle tree view / GlueProjectSave whenever a new file is added to a folder that matches wildcard
- [x] Handle in the tree view / GlueProjectSave whenever a file is removed from a folder that matches a wildcard
- [x] Codegen whenever a new file is added to a folder that matches wildcard
- [x] Codegen whenever a file is removed from a folder that matches a wildcard
- [x] Handle reload when wildcards do not change on disk, but on a file that has wildcards
- [x] Handle reload where new wildcards are added on disk
- [x] Handle reload where existing wildcards are removed on disk - this may result in auto created RFSs also being removed
- [x] Make sure incremental reloads still work despite there being wildcard-matching auto-created RFS's 

... add more here while working on the feature.

**Comment by vchelaru** [comment]
The first pass on this feature is finished on the WildcardRfs branch.

16c28af5076c2f40128ff8e44fc3bbe985155fe0

Note the following restrictions:

* Currently only wildcards in GlobalContent are supported. Not yet in Screens or Entities. 
* Currently same-named files cannot be added. They must have different file names, even if the extensions differ. 
* Currently all files must be inside the Content folder somewhere.

If this is good enough to at least help with some of the problems you are encountering, please give it a shot and let me know.

Also, please let me know if any of the limitations above are needed to be solved. 

As mentioned above, the way to test this feature is to manually modify the .gluj file and add an entry with the desired pattern.

**Comment by mfigueirido** [comment]
Made a test this morning. Modified my .gluj project to add a wildcard file reference that searches for files recursively inside GlobalContent. I'm attaching the change just in case I'm typing it wrong or placing it were it isn't:
![imaxe](https://user-images.githubusercontent.com/24922404/167290452-b0212bab-5b41-4b32-ad38-27fd0436dcdf.png)

After that I open Glue and this shows up:
![imaxe](https://user-images.githubusercontent.com/24922404/167290502-929ed504-0ff8-428e-9330-b36d4cf77f13.png)

Please note that I didn't remove the previous explicit file references present in the project.

> Also, please let me know if any of the limitations above are needed to be solved.

Although supporting Entities and Screens seems like a logical thing to do engine-wise, the only limitation that would affect us is the same name issue. It doesn't affect us for files inside GlobalContent so we can test with those files for the time being.

**Comment by mfigueirido** [comment]
Got a little more time to fiddle with this. Seems like the first time GetFilesForWildcard() is called remainderSuffix is null and calling .Contains() causes the exception.

![imaxe](https://user-images.githubusercontent.com/24922404/167292547-9b57180c-dc9e-4d95-816b-2f310f41a9f7.png)

Modified the entry to include a single asterisk (*) to disable recursivity, tested again and it was successful. This showed on the output window:

> 12:50:00.2 - Added GlobalContent/LTDustAnim2.png to DeadvivorsOGL as content
> 12:50:00.2 - Added GlobalContent/MainFont.bmfc to DeadvivorsOGL as content
> 12:50:00.3 - Added GlobalContent/Mousetrap2.bmfc to DeadvivorsOGL as content
> 12:50:00.4 - Added GlobalContent/Mousetrap2Outline.bmfc to DeadvivorsOGL as content

It would be nice if the content added with wildcards had a different icon so you can distinguish it from explicitly added files though.

Edit: Ok made another test to check how Glue behaves while doing changes to the file system while it is running. 

- Modified the LTDustAnim2.png texture that was added with the wildcard upon load and this message showed on the output window:
![imaxe](https://user-images.githubusercontent.com/24922404/167293373-11885da6-9641-4f04-9206-98d4a043edc2.png)

- Renaming a file appeared to remove the old reference and add the new one successfully.
- Deleting a file appeared to remove the reference successfully.
- Adding a file appeared to add the reference successfully.

**Comment by vchelaru** [comment]
Thanks @mfigueirido I have solved the original issue (the null reference exception).

The second issue was caused by changes resulting in the file being re-added. I've solved this by making sure the file doesn't already exist when doing an add. After the fix, I made changes to a file and everything worked well.

Can you try again with the latest on the WildcardRfs branch?

**Comment by mfigueirido** [comment]
Thanks @vchelaru, I'm doing more testing.

The first thing I did was remove all previously explicitly added content in Glue because I just want everything to be automatically synced. There's some details -which aren't critical at all- I realized could be improved while doing this:

- Deleting files from Glue was cumbersome because you can't select many files and delete them all at once. 
- Deleting subfolders wasn't an option because Glue won't let you keep the files on disk and doesn't appear to remove the file references from the project either.
![pregunta cartafoles](https://user-images.githubusercontent.com/24922404/167399526-576d269c-c049-4a81-a9a6-5a4a8a845043.png)
![erros cartafoles](https://user-images.githubusercontent.com/24922404/167399555-0bfa5c2c-d577-4ddf-9598-be39b89895f8.png)
- Every time I answer the "What would you like to do..." question the tree view would select the Screens node and I would have to scroll all the way down again.
![segunda pregunta cartafoles](https://user-images.githubusercontent.com/24922404/167399595-13e3e45a-a7bb-49ff-86ab-6ce7dbfec518.png)
![screens](https://user-images.githubusercontent.com/24922404/167399611-6a11c94e-a98b-480b-865d-30d2eb174d39.png)

Because of this I ended up removing the content by editing the .gluj myself.

After that I added these entries:

    {
      "Name": "GlobalContent/**/*.png",
      "IsSharedStatic": true,
      "DestroyOnUnload": false,
      "HasPublicProperty": true,
      "ProjectsToExcludeFrom": []
    },
    {
      "Name": "GlobalContent/**/*.fnt",
      "IsSharedStatic": true,
      "DestroyOnUnload": false,
      "HasPublicProperty": true,
      "ProjectsToExcludeFrom": []
    },
    {
      "Name": "GlobalContent/**/*.ogg",
      "IsSharedStatic": true,
      "DestroyOnUnload": false,
      "HasPublicProperty": true,
      "ProjectsToExcludeFrom": []
    },
    {
      "Name": "GlobalContent/**/*.wav",
      "IsSharedStatic": true,
      "DestroyOnUnload": false,
      "HasPublicProperty": true,
      "ProjectsToExcludeFrom": []
    },

Opened Glue and all files -including subfolders- were added successfully and they were showing with the new icon for synced files. The game run fine.

Decided to test the functionality of adding files outside GlobalContent folder so added this to the .gluj:

    {
      "Name": "Resources/**/*.fmx",
      "IsSharedStatic": true,
      "DestroyOnUnload": false,
      "HasPublicProperty": true,
      "ProjectsToExcludeFrom": []
    },

After loading Glue the files were added but they were displayed -as I expected- mixed with the other files inside Global Content Files instead of being shown on their own Resources folder.
![mistura](https://user-images.githubusercontent.com/24922404/167399693-41e6dd50-8fad-48b3-a6f1-53b70ad80a40.png)

This is what I meant by confusing previously. I think Glue should display all the files just as they are laid out in the file system -maybe taking Content as the root folder and showing everything from there-. This would mean it no longer matters where the file is placed in order to consider it global, entity or screen content, that would simply be a property on each file and all of them would be shown on the same section named "Content".

If this wasn't possible -it's probably too big of a change- we would just put all our files under GlobalContent in order to be shown the way it's expected.

All that said... The feature works well and will be a huge time saver for all kinds of game projects.

**Comment by vchelaru** [comment]
Going to close this issue for now. We have other issues to cover some of the missing features mentioned above.
