### ISSUE TITLE
Glue doesn't restart the game when a TMX file is modified

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#373]
In the past the game would be automatically restarted in the same screen you were (hot reloaded) when a file like a TMX was modified from the outside. It doesn't work now. It doesn't matter whether "Game Edit Mode" is enabled or not. Tested on a build made from source on 28/01/2022.

**Comment by vchelaru** [comment]
Thanks for logging this. The reason this has changed is because the communication between Glue<->Game has changed considerably since the new level editor was added. I've updated the plugin to now enable restarting the game when edit mode is enabled, but not turned on. Some users may not want this, so it's an option that can be toggled.

The commit below adds this option (this is new, was not available on your build of Glue), so once you update the FRB repository (don't forget Gum), this will be available.

![image](https://user-images.githubusercontent.com/729631/151616648-e5d6fcd2-b6f4-4d55-83ba-a87445cd93f9.png)

New projects will have this enabled by default, but old projects will have it set to false, so you will need to check it to enable it.

593cbc0f07e5e93fa892b83080555fdbaff6d973
