### ISSUE TITLE
GLUJ keeps being renamed and version control loses track of the file

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#403]
"Load recent" stores it's paths in lower case:
![imaxe](https://user-images.githubusercontent.com/24922404/152836605-ba9021e5-1002-4d72-8e28-406c84fb952a.png)

And when you load a project through this menu it renames the gluj file to lower case... So if you had your project named DeadvivorsOGL it will rename the gluj to deadvivorsogl and the version control will lose track of the file:

![imaxe](https://user-images.githubusercontent.com/24922404/152838973-c0a39db4-5860-43de-ba4c-478f2199e78f.png)

Days ago I tried just adding it without caps to the version control but while doing a random operation the file was back to being named with caps.

It would be cool to solve this inconsistency.

**Comment by vchelaru** [comment]
Details - This is likely happening because the current glue project is being stored as a string and not FilePath, so it is losing its case. This can also be seen by creating a new project with capitalization in the name, and then reloading the project and observing that the title is all lower-case.

This can be solved by moving to FilePath throughout the code that stores and displays file paths and don't use the Standardize method on the name anywhere.

**Comment by vchelaru** [comment]
Fixed.

8b8fb96a9b50b8259e1156bffc56b6c97d031a64

![image](https://user-images.githubusercontent.com/729631/152916317-c0897ac8-7e48-4a5f-8189-8e133c991d34.png)
