### ISSUE TITLE
Glue displays an error after solution is saved from Visual Studio

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#407]
1. Open Glue.
2. Open Visual Studio and make a change such as adding or removing a file to the project.
3. Hit the "Save All" menu in Visual Studio.

Glue will start reloading the project and a series of errors relating to content files will be shown on the output window:
![imaxe](https://user-images.githubusercontent.com/24922404/152994797-680d4688-2de4-4d24-916c-915e4ce1b010.png)

After this the game cannot be run from Glue. The project needs to be closed and opened again.
Furthermore, this complete reloading after a VS change can be problematic when the project is screen heavy because the error reporter screen checking is very slow.

Edit. This shows up at the top of the output window:
![imaxe](https://user-images.githubusercontent.com/24922404/152997572-7e763b5d-51dc-4580-b63f-b9efc943a642.png)

**Comment by vchelaru** [comment]
I believe this was ultimately caused by the TaskManager allowing multiple tasks to run simultaneously. This is being tested in the `NewQueue` branch. The commit that has the changes is bbac9dd3ffb3db8c9bfa5dd2a1c765fd5436e93d. Since this is a big change to Glue, it's being kept on that branch for a day or two until it's tested out in a real project.
