### ISSUE TITLE
Glue should allow you to set the level (camera) background color in edit mode

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#483]
When editing a level, you should be able to set the level's background color in Glue

**Comment by vchelaru** [comment]
This was mostly already functional if you add a Camera object to the screen. There were a few things broken with camera variable assignment but now those are fixed.

d501af9d958c46501fabd6f235ddd85ee67bedc9
![16_13 54 48](https://user-images.githubusercontent.com/729631/158679368-240f710c-c5d2-4a1f-9c58-6c3a25883d3a.gif)

**Comment by profexorgeek** [comment]
Re-opening for discussion purposes.

- I know that _functionally_ background color is a camera property. But _practically_ does a developer think of setting the color as a level property?
- I've never added a camera to a level and wouldn't expect to add a camera entity just to set the background color for level 4 (for example). How would I come to the conclusion that my level _needs_ a camera entity when new project wizard "magically" sets up camera control for me?
- What if I want a custom color that's not in the XNA colors enum?

These could be spun out into separate issues. And it's fair to say "this is the pattern for now" and re-close the issue. Just bringing up some scenarios in case you want to dig into this more.

**Comment by vchelaru** [comment]
Good comments.

## Answers

> I know that functionally background color is a camera property. But practically does a developer think of setting the color as a level property?

Technically it's not a level property, but rather, a property on the camera. If you want it to be a level property, you can set it on the derived camera object in the level. If you would rather have it be constant across all levels, you can set it on the Camera as defined in the GameScreen. If you want it to be a global value, then you would (currently) have to do that in custom code.

For this to change, there would have to be a color property on the Display Settings tab but...there's some technical reasons why that may be a bit of work currently. See below for a deeper discussion of BackgroundColor limitations.
> I've never added a camera to a level and wouldn't expect to add a camera entity just to set the background color for level 4 (for example). How would I come to the conclusion that my level needs a camera entity when new project wizard "magically" sets up camera control for me?

This is unfortunately not very discoverable, aside from the fact that now there are docs that cover this, and this issue is here which may come up in searches. I think that this could be made more discoverable, but as mentioned above, there are some technical restrictions that make this not suitable to have in the top-level Display Settings. 

> What if I want a custom color that's not in the XNA colors enum?

This is a current limitation of the WPF property grid implementation. Objects like Sprite which have RGB values that can be set independently are able to do that because they expose Red, Green, Blue in their classes, which Camera does not. Therefore, to fix this, the wpf property grid implementation used here would need to be updated. Possible, but a bit of work.

## BackgroundColor limitations

Currently when setting the BackgroundColor on a Camera, that will both apply to the background of the camera *and* the pillarbox/letterbox areas. For instance, consider the following game which is set to run at 16:9, but the window is resized to a taller aspect ratio. The background color is red:

![image](https://user-images.githubusercontent.com/729631/158689777-d16f9566-fcb4-488b-b978-2acb86aa3470.png)

Most games would prefer to have a black edge, but due to MonoGame limitations, this is how clearing works. Therefore, using the BackgroundColor as a final solution for game backgrounds will not work on all games - some games may want a fixed aspect ratio. In that case, the background color should be set through tiles or a large sprite.
