### ISSUE TITLE
Editor: Quick value changes should not fail to preview

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#486]
I have exposed the Red, Green, and Blue values and set the color mode to modulate on an entity that contains the sprite. Sometimes when I update the color values, the update is not applied. I can't figure out exact repro other than it happens with quick value changes.

I'm reasonably confident the slider is spamming the network connection with updates that arrive out of order. Sliders should probably only send an update on mouse release.

Example, the end of this gif is the wrong color:

![glue-no-update](https://user-images.githubusercontent.com/711100/158293295-1a8f2ea8-d5a9-4478-a80c-e89f5cb1ad2f.gif)

**Comment by profexorgeek** [comment]
UPDATE: I was also able to make this happen with the rotation control, which reinforces my "spamming the network" theory.

**Comment by vchelaru** [comment]
I don't know if this is related, but dragging the slider creates TONS of tasks that seem to accumulate if the slider is dragged enough. I think this can be improved.

![15_10 58 40](https://user-images.githubusercontent.com/729631/158431323-88be97b3-58cd-4fd3-872c-06538474c932.gif)

**Comment by profexorgeek** [comment]
Right, all of those tasks are created and, presumably, broadcast through the network to the editor. Network throughput on same device is really fast but spamming _that many_ messages is likely to result in some messages being received out of order. If messages are received out of order than the final state of the editor may not match the final state of the slider/knob controls.

**Comment by vchelaru** [comment]
Fixed!

6c98178b1f2e25af7394b9cac2db6c7ac76dd7ff

There were a number of problems:

1. (really big one) - the tasks were not guaranteed to run in order due to a change in how the task manager processes tasks. Tasks of the same priority could get shuffled due to the sorting of tasks being unstable. This has been fixed so that fifo tasks will truly be fifo.
2. High resource usage due to a bug in the task manager which was not respecting the uniqueness of AddOrMoveToEnd tasks. This means that sliding the slider caused the error window to refresh itself hundreds of times, and the .gluj file was also being spammed.
3. The current element was serialized and sent to the game, causing a TON of json to be serialized. I'm actually not sure why this was happening, perhaps it was for good reason, so I put a comment and if this causes issues the comment will help me remember the change.
4. There's a bug in the slider (seems to be a WPF issue) where high-frequency values pushed from the UI can cause the slider to hop around. I've cut the frequency of the slider to 100 ms per update. This isn't strictly necessary anymore for performance reasons, but it does fix the jumpy slider behavior.

In all, this fix has a lot of other benefits for FRB Editor so - it's a big one!
