### ISSUE TITLE
FRB Editor should build XNBs for FBX files just like it does for WAV and MP3s

### ISSUE THREAD

**Issue by vchelaru** [vchelaru/FlatRedBall#492]
Had to zip this to upload to github, but it contains a test FBX if unzipped.

[ship3.zip](https://github.com/vchelaru/FlatRedBall/files/8289422/ship3.zip)

**Comment by profexorgeek** [comment]
I'll expand on this since I did preliminary testing. Here's how I got FBX rendering working in FRB. The ship model you attached was created in blender, has no textures and is just vertex shaded with materials and exported as FBX (or something like that, I don't know 3D terms and concepts very well).

![image](https://user-images.githubusercontent.com/711100/158878777-267e9323-2742-43cf-86c7-6ceab3b36821.png)

1. Add the FBX to Global Content
1. Create an Entity and add the FBX to the Files
1. Add an instance of the Entity to a GameScreen
1. **Glue does not build XNBs for FBX files: manually build an XNB using the MCGB tool and include the XNB in your csproj**
1. The Entity should implement `IDrawableBatch` in Glue
1. Set the entity instance Z to 650 to bring the entity closer to the camera - the ship is really small!
1. Satisfy the interface by implementing a `Draw` method. This makes core MonoGame calls to accomplish rendering. Draw code below...

```csharp
public void Draw(Camera camera)
{
    // create a world matrix based on a matrix from the parent position and rotation matrix
    var worldMatrix = this.RotationMatrix * Matrix.CreateWorld(this.Position, Vector3.Forward, Vector3.Up);
            
    // draw all meshes 
    foreach(var mesh in ShipModel.Meshes)
    {
        // it might be possible to create a single BasicEffect,
        // assign it to all meshes, and move it out of the draw call
        // but the effect will probably need various matrices updated
        // whenever the position or camera changes!
        foreach(BasicEffect effect in mesh.Effects)
        {
            effect.View = camera.View;
            effect.World = worldMatrix;
            effect.Projection = camera.Projection;
        }
        mesh.Draw();
    }
}
```

**Comment by vchelaru** [comment]
The steps above are now simpler due to commit

43fa1e9578ab80ab3f46978b5b6e063718771516

This commit enables FRB Editor to accept FBX files. It recognizes those files as needing content pipeline support, so it automatically:

1. Builds the XNB for the FBX when the FBX is added or when it is modified (just like XNBs for music or PNG files)
2. Adds the XNB to the Visual Studio project so that it is copied over when built
3. Creates a Model static object in the Screen/Entity/GlobalContent that contains the FBX
4. Generates code to load the FBX XNB into the Model object.

With these changes, the steps above become the following:

1. Create an entity
2. Add the FBX to the entity
3. Add an instance of the entity to the GameScreen or Level
4. Make the entity implement IDrawableBatch in FRB Editor
5. Satisfy the interface by implementing a Draw method. This makes core MonoGame calls to accomplish rendering. Draw code below...

```
public void Draw(Camera camera)
{
    var scaleMatrix = Matrix.CreateScale(ScaleX, ScaleY, ScaleZ);
    // create a world matrix based on a matrix from the parent position and rotation matrix
    var worldMatrix = scaleMatrix * 
        this.RotationMatrix * 
        Matrix.CreateWorld(this.Position, Vector3.Forward, Vector3.Up);

    // draw all meshes 
    foreach (var mesh in ship3.Meshes)
    {
        // it might be possible to create a single BasicEffect,
        // assign it to all meshes, and move it out of the draw call
        // but the effect will probably need various matrices updated
        // whenever the position or camera changes!
        foreach (Microsoft.Xna.Framework.Graphics.BasicEffect effect in mesh.Effects)
        {
            effect.View = camera.View;
            effect.World = worldMatrix;
            effect.Projection = camera.Projection;
        }
        mesh.Draw();
    }
}
```

Notice I'm creating a scale matrix using ScaleX, ScaleY, and ScaleZ values. You can add those to your object if you want to control it in FRB Editor/code. Also, if you make the entity implement IScalable3D, then the FRB editor will recognize that and add handles for you.

@profexorgeek blogging? 😄
