### ISSUE TITLE
FRB Editor should provide visual texture coordinate selection

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#494]
IMO this is a major feature gap and a high-priority enhancement.
Right now to specify texture coordinates you must either:

1. Specify numerical coordinates individually, from a separate application
2. Specify an animation chain, which you create in a separate application

For the editor to be effective at creating both Entity and level (Screen) layouts, it needs to support mapping texture coordinates within the editor using similar tools to what both Gum and the Animation Editor provide (snapping, magic wand, etc)

**Comment by vchelaru** [comment]
For this to happen, the editor must have some kind of visual editor support. There's lots of options here:

1. Embed an external .exe. This is probably the most work, but I'm adding it here as an option because one could argue that this would move the tech used for editor<->game communication forward. However, we use this in game because it's the best way to allow a user's custom code to run in a preview. Otherwise, this communication makes debugging way more difficult so I don't think it's the way to push things forward.
2. Use a WPF-based drawing system. WPF drawing can be fast, but it doesn't uses its own custom rendering language which may not carry over. Also, for more complex things we'd be re-making layout logic like what exists in FRB and Gum.
3. Use SkiaGum inside a canvas inside WPF. This has the benefit of being very portable, and the rendering library syntax is identical across SkiaGum and regular Gum which is used in the main Gum editor, texture coordinate selection window in Gum, and AnimationEditor.
4. Include MonoGame WPF and use a MonoGame window inside WPF. I don't know how popular this is or how thoroughly tested. At the time of this writing it hasn't had commits in almost 3 years https://github.com/craftworkgames/MonoGame.WpfCore

Although this is a small feature, it does lay the foundation for future embedded editors in FRB so I'm taking extra time to decide. At this point my vote is SkiaGum because of the following:

1. It supports lots of useful visual features used by editors right out of the box including:
    * Antialiasning
    * Superior font rendering
    * Thick lines (more than 1 px thick)
    * Filled shapes (rounded rectangles, filled circles)
    * Arcs
    * Gradients
    * Dropshadows
2. It supports all the Gum layout engine using SkiaGum
3. It can be drawn on lots of surfaces making it cross platform
4. It is efficient (should be close to efficient as XNA)
5. It will benefit from all the SkiaGum improvements being made at Vic's work
6. At least according to what Vic has tested, multiple skia canvases can exist and not eat up a lot of resources. We use it heavily on mobile so it should be fine in a desktop editor.

**Comment by vchelaru** [comment]
Mock:

![image](https://user-images.githubusercontent.com/729631/170526290-f67a52cd-86fa-43ce-8ed0-0f18da53fe2c.png)

**Comment by profexorgeek** [comment]
To recap reasons why  I made it a floating window instead of embedded:

1. The expected workflow is:
   - be creating an entity/screen
   - create a sprite
   - map the sprite to coordinates in a larger spritesheet
   - create the next sprite (quickly in succession)
1. In this workflow you don't want to constantly switch back and forth between the Variables tab (where you're doing most of the work) and a texture-mapper tab
1. In this workflow you don't want the editor to be constantly unloading and reloading or switching tabs in the center space
1. So this texture-mapper is relevant for a specific duration during the workflow, not constantly.

With this in mind, the texture-mapper should load quickly, remember your last-used texture (but offer the ability to select texture), have similar snapping and other controls to the animation editor, go away quickly when you close the window (or click an apply button?)

This should allow rapid addition and mapping of sprites to entities and screens

**Comment by vchelaru** [comment]
I spent some time adding SkiaGum to Glue project and ran into a few issues:

1. SkiaGum.Wpf depends on .NET Core 3.1, but Glue is still .NET Core 3.0. I was able to create a copy SkiaGum.Wpf.NetCore3_0 easily because the project is very small.
1. SkiaGum is a project that has no dependencies aside form ToolsUtilitiesStandard, which is already part of Glue. However, to avoid needing a dependency on MonoGame, SkiaGum includes its own math objects like Vector2/3/4, Matrix, etc. This causes naming conflicts with Glue, so what's needed is a new SkiaGum.MonoGame library which is the same as SkiaGum but it excludes the Xna objects. This would use wildcards to include/exclude everuthing.

**Comment by vchelaru** [comment]
First pass:

cf61479384e10bd1b5a689819b0a83d0e17d9880

![2022_June_19_131749](https://user-images.githubusercontent.com/729631/174499036-d35868c3-af7b-4d0a-aab8-531a0b4e2c26.gif)

Not all items in this card are finished, but this is a big first step.

**Comment by vchelaru** [comment]
Done

f58eb37bee51c03a5991ebd99cd0b529fa5d86a5
