### ISSUE TITLE
Button to add Forms shown for projects already using Forms

### ISSUE THREAD

**Issue by patridge** [vchelaru/FlatRedBall#512]
It seems weird to see that option from the GumProject.gumx > Gum Properties tab when I'm operating in a project that was a new **UI (FlatRedBall.Forms)** project type.

![Screenshot of Glue showing the Gum Properties tab when the GumProject solution is selected in the Explorer, with the Add Forms to Project button highlighted.](https://user-images.githubusercontent.com/713665/160969607-fd0cce96-9b40-44a2-ba6c-c6207d26a706.png)

Not sure if it's possible to identify a project already using Forms, but it might be worth not showing that section to avoid confusion.

## Steps

1. Create new **UI (FlatRedBall.Forms)** project
2. In the Explorer tab, select **Global Content Files** > **GumProject.gumx**
3. View the **Gum Properties** tab where there will be a **Add Forms to Project** button in the **FlatRedBall.Forms** section

**Comment by vchelaru** [comment]
This is intentionally available since users can click it again to fix corrupt files or add new controls which may have been added in the future. 

I've modified the button to indicate this to avoid future confusion.

![image](https://user-images.githubusercontent.com/729631/160974541-1c4d2024-16d5-4bd6-82dc-be5d1a3691c5.png)
