### ISSUE TITLE
Flip Horizontal should work correctly

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#515]
Repro:

- Create an entity with two sprites
- Have one of the sprites set to Flip Horizontal
- The preview looks correct
- Build the game
- The sprite is not flipped horizontally

Gif:
![flip-horizontal](https://user-images.githubusercontent.com/711100/161338954-9df1364a-85fa-4dc1-80cb-b4e4c2e8af84.gif)

**Comment by vchelaru** [comment]
This is happening because the Sprite uses an AnimationChain.

The flip behavior can be controlled on the Sprite:

![image](https://user-images.githubusercontent.com/729631/161346959-a40df020-fd43-4fd3-9f93-029a86590d76.png)

Note - I realize that this is a little hard to find since it's at the bottom, and it uses "Ignore" instead of "Use" for Position, so newer versions of FRB gluj files (15 and newer) will now have the variable showing right under the location, and using a matching name convention "Use":

![image](https://user-images.githubusercontent.com/729631/161347053-f25fc97e-e2cd-4059-97f9-eb00d0fca52f.png)
