### ISSUE TITLE
Glue suggests to remove all content added on VS

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#551]
After removing one file from the Global Content Glue showed this window:
![imaxe](https://user-images.githubusercontent.com/24922404/166446580-5f5e4575-48ac-4c60-8787-8eb52ccfe5bc.png)

Which is basically listing all content files I added to Visual Studio which aren't managed by Glue plus the one I removed on Global Content (the first one). I think those unrelated files shouldn't be showing on that window.

**Comment by vchelaru** [comment]
I have added a lot of files not through Glue to VS and I cannot reproduce this issue. Would you be able to try on a new project, and perhaps see if there are steps that will cause it?

For future research for me - this is handled in GluxCommands.RemoveReferencedFileInternal. Review reference tracking there.

**Comment by mfigueirido** [comment]
Tried to reproduce it again but was unable to do so. There's certainly some specific steps to trigger it... I'll keep an eye in case it shows up again.

**Comment by vchelaru** [comment]
I've reviewed the way the code works, and for future reference I will explain how it works here.

Glue keeps an UnreferencedFiles list which tracks files that are part of the VS project, but not referenced directly or indirectly by any Files (in entities, screens, or global content). This is able to follow the dependency tree recursively so it should properly detect files that are referenced by other files (such as PNG files referenced by Gum files).

Whenever a file is removed, a snapshot is taken of the UnreferencedFiles list. Then the file is removed, and a new UnreferencedFiles list is determined. The old and new UnreferencedFiles are compared. If there are any files in the new, but not in the old, then Glue assumes that the files have been added to the new UnreferencedFiles because of the File removal from Glue.

This enables Glue to tell you what has changed, without reporting all of the unreferenced files (as shown in the original bug). Of course, there seems to be some bug causing file references to not be tracked properly, resulting in the large set of files showing in the list.

I have made some modifications to the code in this commit which may address capitalization mismatches:

241b4386539760caff62136772a30c5c9f356a2a

This may solve the problem, but if not we will need to look at it together more closely, or see if you can reproduce it in a sample project.

**Comment by mfigueirido** [comment]
Nice! I'll close the issue for the time being. If it happens again and get the repro steps I'll re-open it.
