### ISSUE TITLE
Parme particle emitters don't work in edit mode

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#576]
- Have glue running (in edit mode?)
- Create a new Parme emitter
- Add the emitter to global content
- Add a parme emitter to your entity
- Reference the file you just added in the Emitter Logic dropdown
- Set an Emitter Grouping

Observe these bugs:

- [ ] Parme emitter has no draggable zone
- [ ] Parme emitter does not preview correctly until a rebuild
- [x] Updating X and Y positions does not affect emitter preview
- [ ] Updating X and Y, then choosing a different entity, then returning to the emitter-containing entity crashes the editor

**Comment by vchelaru** [comment]
Tagging @KallDrexx so he is aware of what is needed here:

## Parme emitter has no draggable zone

The reason for this is because the parme emitter does not implement any known FRB interfaces. For the editor to highlight a Parme emitter, the editor must understand where its X and Y origin are. The easiest way for this to be solved is to make the `ParmeFrbEmitter` class implement the IStaticPositionable interface. This has three properties:

1. float X
2. float Y
3. float Z

I realize this interface may not be desirable so it can be explicitly implemented to maintain the XOffset and YOffset properties.

Once this happens I will be able to fix up the editor to support this.

## Parme emitter does not preview correctly until a rebuild

As I understand it, emitters are hardcoded so this may not work until Parme2 or some other solution.

## Updating X and Y positions does not affect emitter preview

Fixed: 71f2f68ce4f9d5f555a0e618673d28fdaa2d7907

## Updating X and Y, then choosing a different entity, then returning to the emitter-containing entity crashes the editor

This is happening because Parme creates an IDrawableBatch in the background for emitter groups, and the GameScreen calls 

`Parme.Frb.ParmeEmitterManager.Instance.DestroyActiveEmitterGroups();`

There's no way for the editor to know that it should call this in the editor screen because the editor screen is a completely custom screen with no codegen, so plugins like the parme plugin cannot inject the DestroyActiveEmitterGroups. Nor can we hardcode that call because there's no way for us to know that they should be removed.

One alternative is for Glue to manually kill any IDBs that are still around but that may hide bugs where the objects need to be cleaned up. I am not sure how to solve this, need to talk to @KallDrexx

**Comment by vchelaru** [comment]
I spoke to @KallDrexx about this, and he will be adding IStaticPositionable support to parme emitters. 

I will be adding an event for whenever screens are destroyed so that parme can clean itself up to fix the crash.

**Comment by vchelaru** [comment]
@KallDrexx I've added ScreenManager.AfterScreenDestroyed, which can be +='ed in Game1 generated code.

0915526e9d7eafd1f8a9447027b716022e4289d3

You will want to add some code to Game1.Generated.cs to clear out all parme emitters. This shows you how:

https://flatredball.com/documentation/tools/glue-reference/code/game1codegenerator/

It should generate code like this:

```
ScreenManager.AfterScreenDestroyed += (screen) => Parme.Frb.ParmeEmitterManager.Instance.DestroyActiveEmitterGroups();
```

Of course, you'll also want to remove the custom generated code in every screen's Destroy that calls DestroyActiveEmitterGroups ... well, I suppose it doesn't matter either way, it just means that will get called 2 times which is unnecessary.

**Comment by vchelaru** [comment]
Checked in one more fix to solve this issue:

f9e64129745b7fd08af377ced860d2ac5cd9d798

There are some limitations to this implementation: The user cannot select a parme emitter in the game by clicking on it. Instead, the user must select the emitter in the FRB editor tree view.

A selected parme object cannot be moved by drag+moving it in game. Instead, its X and Y values must be changed in the editor. 

### Selecting a parme object in game

When the user is editing in a screen, the game loops through all objects to see what is selectable. This is done in SelectionLogic.GetAvailableObjects. If editing a screen, then this checks all SpriteManager.ManagedPositionedObjects (toplevel only)

When the user is editing in an entity, this checks the children of the entity using the FlatRedBall parent/child relationships.

Parme objects do not exist in these lists since they are not PositionedObjects, so they will not be clickable.

### Moving a parme object in game

Once a parme object is selected, it will show up as highlighted in game. But if the object is moved, the live edit code interacts with the X and Y values of the selected parme object. It then sends that back to Glue, which receives X and Y values and tries to apply these values to the Parme object. Unfortunately, the parme object has "XOffset" and "YOffset" instead of "X" and "Y", so these values get thrown away.

In the future, there could be a translation between X -> XOffset by a plugin, but that's for a later day.
