### ISSUE TITLE
Selection hitbox and rectangle are wrong for 90 degree objects

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#627]
I have a simple component that has a single sprite. When I add it to another entity and rotate it by 90 degrees, the hitbox becomes misaligned and it doesn't properly click to select. See gif for demo:

![rotation-hitbox](https://user-images.githubusercontent.com/711100/176585371-20733ae1-2b7c-496b-a4c5-16113beb0537.gif)

**Comment by vchelaru** [comment]
There are two problems here:

1. The selection is not properly considering rotation on entities.
2. The highlight is not displaying the bounds correctly when rotated (the Sprite is cut-off).

To fix this, we'll switch the selection logic from using rectangles to using polygons, so that rotated sprites can be selected properly.

This has been done here:

12c1358c953034c47e2b087e8404c17cd71f1ac4

The next step is to use those internal polygons to determine real min and max X/Y values so that we can do highlights considering rotation. This one is a little trickier...

**Comment by vchelaru** [comment]
Fixed

![30_18_42_10](https://user-images.githubusercontent.com/729631/176801066-e3d60c0f-000d-4bac-a583-416f582fa83b.gif)

6ee71f5af7df32c9792c2274c69fa0d71e4c3e8a
