### ISSUE TITLE
Editor should not allow moving items locked in a parent screen

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#628]
Repro (can use Masteroid as test)

1. Have EntityX in a parent screen
2. Lock EntityX for editing in parent screen
3. Create deriving screen
4. EntityX can be dragged around

Expected outcome: EntityX is locked in all deriving screens
Actual outcome: Can select and drag EntityX in child screen

**Comment by vchelaru** [comment]
While this is a simple issue conceptually, this gets trickier because it requires being able to climb the inheritance path in-game on the NamedObjectSaves. At the time of this writing, only the current object (Screen or Entity) is sent over to the game, and the game doesn't know about the base Screen/Entity.

While a simple work-around could be done, this is an opportunity to pass over the entire Glue project from Glue to the game. This means adding:

* GlueProjectSave
* ObjectFinder
* GlueElementFileReference

This has been the plan all along, so this bug might as well be the catalyst.

The general flow will be:

1. When the game first runs and gets switched to edit mode, it checks if the ObjectFinder.GlueProjectSave is null. If so, it will load the .gluj and all associated Screen/Entity .jsons. This might be a little slow, will have to test.
2. The ObjectFinder will be given reference to the GlueProjectSave that is loaded.
3. Whenever a new NamedObjectSave or GlueElement is sent over from Glue, that should replace the one stored in the GlueProjectSave. This probably doesn't need to use Compare.NET for specific property replacements because the game is (currently) built to expect object references to change all the time rather than they stay the same.
4. Implement ObjectFinder's `GetPropertyValueRecursively` method. The ObjectFinder does not need to be fully implemented, that would take a long time. Instead, just have this one function work to prove out the system and to solve this particular bug.
5. Have the code that checks whether an object can be clicked use the ObjectFinder's GetValueRecursively rather than the direct value on the NamedObjectSave.

Also, note that currently FRB editor doesn't properly show if IsEditingLocked is inherited, so it should also use GetValueRecursively in the DateUiGrid.

This work will move this issue forward as well:

https://github.com/vchelaru/FlatRedBall/issues/589

**Comment by vchelaru** [comment]
Fixed

66a272e4cbcf6b1ab4bb1c3527bb5eb98c430d5e
