### ISSUE TITLE
Update FlatRedBallMedia FRBeefcakeSpritesheet png to include more edges and multiple cloud/solid themes

### ISSUE THREAD

**Issue by vchelaru** [vchelaru/FlatRedBall#664]
The current implementation of the art needs some improvements:

1. The solid collision is potentially confusing for people who have played mario games like Super Mario Bros 2, Super Mario Bros 3, or Super Mario World. Is this tileset solid or cloud? 
![image](https://user-images.githubusercontent.com/729631/180894969-876c1fb1-3e88-4180-994d-6d35bf8ae781.png)
According to Super Mario World, this would be cloud. Super Mario World has grass edges to indicate solid, as shown in the following images:
![image](https://user-images.githubusercontent.com/729631/180895226-829dc230-5c22-4199-a1d9-af17a51aca31.png)
![image](https://user-images.githubusercontent.com/729631/180895379-7bc6ac7e-f4e7-474d-95e7-beb219188df8.png)
Notice that the tiles are identical, but there are green "borders" that block the player from walking and overlapping dirt tiles. We can either differentiate between cloud and solid with some kind of art, or create borders to indicate one vs another.
1. We need 2 cloud and 2 solid collision *variants*. This means that both would be solid or cloud collision as far as gameplay is concerned, but they would look different. This is so that users can learn how to have different types of solid collision in the same level. This is common in games. For example, these both are solid collision:
![image](https://user-images.githubusercontent.com/729631/180895786-5aa9f980-ebe0-48a5-b349-4bc8af1fea07.png)
In this case, variants are not referring to different biomes. If you want to create multiple biomes, that's totally cool, but not needed for this upgrade.
1. All solid collisions should have *edge rules* supporting convex and concave shapes. Currently convex shapes like stair steps are not supported, which makes it hard to create levels.

**Comment by profexorgeek** [comment]
I'm not sure what you mean on #3 that stair steps are not supported. I currently have what I refer to as inner and outer corners, which covers every variant you need to build any shape terrain _as long as a single tile doesn't have more than 2 edges_.

On the sheet:
![image](https://user-images.githubusercontent.com/711100/181026480-5b21d723-6282-432e-a3fb-4315d0234e28.png)

Mocked up as stairs:
![image](https://user-images.githubusercontent.com/711100/181026909-b02d455b-b7f8-45c3-8235-6c5cd5342696.png)

**Comment by profexorgeek** [comment]
How's this. I made sure to draw some stairsteps so you didn't get scared.

![image](https://user-images.githubusercontent.com/711100/181038102-80ab1755-b1e3-488b-8c03-9d6a21097ea3.png)

1a: solid collision variant 1
1b: solid collision variant 2
2a: cloud collision variant 1
2a: cloud collision variant 2
3: actual cloud

Part of the reason I've never designed cloud collision as dirt is because Tiled terrain doesn't support it. You can do it with the new custom rules system but when using terrains you'll have to manually draw the grass across the middle bits of terrain. Also, in the first mario games, the only cloud collision was clouds. Dirt that you could walk through started with Mario 2 in the mario games but was also present in Contra. In my personal art, I avoid dirt that you can walk through because it reads poorly and also requires extra work to create since Tiled Terrains don't support it.
