### ISSUE TITLE
Create new Glux version which will create plurals instead of "List" for collisions

### ISSUE THREAD

**Issue by vchelaru** [vchelaru/FlatRedBall#795]
![image](https://user-images.githubusercontent.com/729631/201697118-2c2ad8da-f022-45d9-b547-d936bbe3d8eb.png)

Currently the behavior is {FirstObjectName}vs{SecondObjectName}

This is safe, but it does make for really long names like

`ThrownBombListVsBombExplosionColliderList`

I propose to instead name collisions plural like:

`ThrowmBombsVsBombExplosionColliders`

This has a bigger impact on shorter-named objects like:

`PlayerListVsTriggerList` -> `PlayersVsTriggers`

Also, the 2 "List" words appear in collision events, so this would shorten them too:

`OnForceAreaListVsEnemyListCollisionOccurred` -> `OnForceAreasVsEnemiesCollisionOccurred`

This will require a new GLUX version as to not conflict with existing events.

**Comment by profexorgeek** [comment]
I pretty much do this exact thing manually because I hate those super long names. I like pluralizing and just adding a `Vs` in the middle.

For the collision events, I think you could shorten it a little further.
Instead of:
`OnForceAreaListVsEnemyListCollisionOccurred`

Why not:
`ForceAreaVsEnemyCollided`

Basically the collisions _usually_ aren't plural, their signature will have two single entity types. The `On` doesn't convey any useful information that isn't already captured by the `Collided` verb. And each type name is singular because that's how the method arguments will be. So the pattern is:
`${EntityType1}Vs{EntityType2}Collided"`

**Comment by vchelaru** [comment]
Additional notes;

Currently when adding a collision event, the event window appears. I've never changed any settings on this window before, I always leave the defaults. I suspect everyone else does too, so what's the point of showing the window?

The window is what is deciding default names like the "On" prefix. If we bypass the window:

1. We get more freedom on the naming.
2. It's one less click for the user, and it eliminates the confusion of "should I be changing something here?"

Therefore, the first step is to remove this window altogether and make the event get added immediately.
