### ISSUE TITLE
Add FontCache to .gitignore

### ISSUE THREAD

**Issue by treesgobark** [vchelaru/FlatRedBall#843]
These files in the FontCache folder could be included in the generated .gitignore
![image](https://user-images.githubusercontent.com/6179393/208561294-8ec755bb-fae1-49c3-8769-d921a14fd964.png)

**Comment by vchelaru** [comment]
Initially I agreed with this card but after doing some research I don't think it's a good idea. The reason is because typically FlatRedBall adds entries to .gitignore for files which are generated and which are re-generated many times throughout development (such as .generated.cs) . When working on a typical game, files like .generated.cs files may be re-generated dozens or even hundreds of times on high-traffic elements such as GameScreen, and having those diffs in the repository adds a ton of noise.

By contrast, FontCache files are generated once and are never generated again (unless the files are explicitly deleted). They are also actually directly referenced by the game so they need to be on disk. To clarify, Gum considers these files a "cache" because it can re-generate them whenever a Gum project is open. However, from the perspective of FlatRedBall, these files are actual content files referenced by the game.

That means that for FlatRedBall, it's not a cache, but real content. The alternative would be to have a FontCache location for Gum, and for FlatRedBall to create a duplicate set of files outside of FontCache...but even then, the Gum rendering system (which runs in-game) looks for fonts in the FontCache location so even that wouldn't work without more work....all to get rid of the name "cache".

Note that it would be possible to exclude the FontCache files, but have FlatRedBall tell Gum to re-generate these files whenever the FlatRedBall project was opened, but this is a lot of added complexity for almost no benefit. Furthermore, this extra step could be somewhat heavy since it requires walking the entire content tree in Gum every time the project is opened. Large projects can already take a while to open.
