### ISSUE TITLE
Consider throwing errors on VM Property type mismatch

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#894]
This may not be possible but I have accidentally done this several times:
`public float SomeThing { get => Get<int>(); set => Set(value);  }`

Note that the property type and the type passed to the `Get` method do not match.

FlatRedBall `ViewModel` allows this. But properties are not set correctly and seem to end up with their default value. This is a pretty big gotcha because it's an easy mistake to make but results in bad runtime values that are hard to debug.

Ideally, this would blow up in your face with a clear exception. I can't think of instances where you want this sort of implicit conversion on a getter. I'm not sure if it's actually possible to detect these mismatches at runtime and throw an error without significant overhead but if it's possible this should be the behavior.

**Comment by vchelaru** [comment]
Since this is breaking behavior, this should not be turned on by default. However, it can now be turned on with the following code:

```
FlatRedBall.Forms.MVVM.ViewModel.DefaultTypeMismatchBehavior = TypeMismatchBehavior.ThrowException;
```

This will result in exceptions being thrown across your app.

I admittedly haven't tested this extensively so I'm not sure if it will result in noisy exceptions, need to see.
