### ISSUE TITLE
Glue shouldn't inject pragma warnings in Game1.cs

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#952]
I think this is a new addition from @dubhlaidh

Recently I noticed that my commit diffs have started having added lines at the top of `Game1.cs`
![image](https://user-images.githubusercontent.com/711100/217307588-f91ba20f-38a4-42ec-9206-108c56e8e1e4.png)

I'm not sure if these should exist at all but either way they probably shouldn't be repeatedly added.

**Comment by dubhlaidh** [comment]
I must not use whatever it is that modifies game1.cs.  It must be taking the current file contents and passing it in there causing dupes.

How about checking the filename for generated first?
![image](https://user-images.githubusercontent.com/10093926/217319507-2a4fe612-55fa-4c8f-8636-f9d2804b8936.png)

**Comment by vchelaru** [comment]
To reproduce this:

1. The game project must be an old glux/gluj version so that generated code is added to Game1.cs. Newer versions of FRB do not generate code here, so it does not reproduce.
2. Changing the startup screen does this, as doing so re-generates the game screen. It may be that any change to Game1 causes this to happen, but I repro'ed it by changing the starutp screen.

**Comment by vchelaru** [comment]
I hope you don't mind me fixing this @dubhlaidh but I did add the code you suggested above and tested it on @profexorgeek 's game.

8d561112c60e9cba0c9034f3367ca7f37ad9f094
